### ISSUE TITLE
Segfault when testing Gosu::Window

### ISSUE THREAD

**Issue by cadwallion** [gosu/gosu#108]
I have been working on unit testing small games in Gosu and have run into a segmentation fault repeatedly under similar circumstances.  It seems that when I try to reuse a Gosu::Window object to test creation of either Gosu::Image or Gosu::Font objects bound to the window object, or when I try to use multiple Gosu::Window objects in the same test suite, I get a segmentation fault.

I have tried closing the window context with the #close method at the end as well and the segfault continues to occur.

Operating System: OSX Lion 10.7.2
Gosu Version: gosu (0.7.40 universal-darwin)
Ruby version: 1.9.3-p0 (using RVM and an isolated gemset with only bundler and gosu installed)

Steps to Reproduce (with output): 
Single, Reused Window Context - https://gist.github.com/1433743
Multiple Window Contexts with Close - https://gist.github.com/1433771

**Comment by jlnr** [comment]
Not only has the `Window` architecture changed a lot since 2013, but `Gosu::Font` and other resources do not require a `Window` to be loaded anymore. Everything should work just fine now. Thanks again for the really detailed bug report!
