### ISSUE TITLE
Gosu::Font has too simple letterspacing

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#11]
<pre>
<b>What steps will reproduce the problem?</b>
1. Use font 'Monaco' to draw the letters a-z.
2. Notice the broken rendering of u, the gap between f and g, r and s, w and x etc.

What version of the product are you using? 0.7.5 
On what operating system? OS X

It would be nice to be able to bundle fonts in a platform independent manner.

</pre></br>Original link: http://code.google.com/p/gosu/issues/detail?id=11

**Comment by alexdovzhanyn** [comment]
Sorry to bump an old issue but I'm experiencing this now and can't find anything online on how to fix this. Are there any updates that have been made that I can use to fix this or is it still unresolved?

**Comment by jlnr** [comment]
@alexdovzhanyn Now is a good time to bump this issue! I've completely rewritten the text rendering backend for the upcoming v0.14. Can you please install the current master branch and see if the issue has been resolved for you? [The `rake gem` command is the easiest way to do this](https://github.com/gosu/gosu/wiki/Hacking-Gosu).

If you are still experiencing issues with the font rendering, I might be able to fix them as part of #448.

**Comment by jlnr** [comment]
TrueType font rendering has been completely rewritten and already merged to master. I am closing this old issue, and will wait for fresh bug reports with the new stb_truetype-based code.
