### ISSUE TITLE
TextArea caret position doesn't take parsed entities/tags into account.

### ISSUE THREAD

**Issue by Spooner** [gosu/gosu#114]
If entities/tags are used in a TextArea then it uses the _full_ string length for caret, etc, not the string's display length, which is a pain to workaround.

e.g.  in a string "hello", arrow keys will move caret from 0..5. In "&pig;" it also goes from 0..5 but should be 0..1

EDIT: jlnr suggests just not supporting entities/tags in textinputs.

**Comment by jlnr** [comment]
Superseded by #304
