### ISSUE TITLE
Gosu::Sample#play_pan not panning in Windows

### ISSUE THREAD

**Issue by Billiam** [gosu/gosu#123]
In Windows, play_pan does not functioning correctly, with all audio on only one channel at a time, depending on pan argument.

High negative and positive pan values will change the volume of the sound in its single channel.

Test case: gosu/feature_tests/SamplePlayTest.rb

**Comment by jlnr** [comment]
I ran the audio tests interactively on Windows yesterday and it could pan audio without issue 👍
