### ISSUE TITLE
Please make openal optional or allow users to disable it when trying to compile gosu

### ISSUE THREAD

**Issue by shevegen** [gosu/gosu#130]
Hi.

I can not install openal right now.

But gosu fails to compile when openal is not installed.

Please allow for gosu to run without audio too. I could want to make a game and never need audio.

It would help me work around the current problem I have with openal 0.0.8

Then openal error, if anyone is curious is:

 gcc -DHAVE_CONFIG_H -I. -I. -I.. -I../common/include -I../include -I../src/arch/i386 -Wall -ansi -pedantic -finline-functions -ffast-math -fomit-frame-pointer -fvisibility=hidden -I/usr/include/alsa -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/Programs/Libvorbis/1.3.3/include -I/Programs/Libogg/1.3.0/include -I/Programs/Smpeg/18.11.2011/include -I/Programs/Smpeg/18.11.2011/include/smpeg -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL -fomit-frame-pointer -frerun-loop-opt -pipe -fPIC -pthread -O2 -MT libopenal_la-x86_floatmul.lo -MD -MP -MF .deps/libopenal_la-x86_floatmul.Tpo -c arch/i386/x86_floatmul.c  -fPIC -DPIC -o .libs/libopenal_la-x86_floatmul.o
arch/i386/x86_floatmul.c: In function '_alFloatMul':
arch/i386/x86_floatmul.c:86:46: warning: use of C99 long long integer constant [-Wlong-long]
arch/i386/x86_floatmul.c:86:5: error: incompatible type for argument 2 of '__builtin_ia32_psllw'
arch/i386/x86_floatmul.c:86:5: note: expected '__vector(4) short int' but argument is of type 'long long int'
arch/i386/x86_floatmul.c:89:46: warning: use of C99 long long integer constant [-Wlong-long]
arch/i386/x86_floatmul.c:89:5: error: incompatible type for argument 2 of '__builtin_ia32_psllw'
arch/i386/x86_floatmul.c:89:5: note: expected '__vector(4) short int' but argument is of type 'long long int'
make[3]: **\* [libopenal_la-x86_floatmul.lo] Error 1
make[3]: Leaving directory `/Depot/Temp/openal-0.0.8/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/Depot/Temp/openal-0.0.8/src'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/Depot/Temp/openal-0.0.8'
make: **\* [all] Error 2

**Comment by jlnr** [comment]
Sorry, closing as "won't fix" after all these years. I can't handle more `#ifdef` cases in the codebase, given the small amount of time I have for maintenance.
