### ISSUE TITLE
Frozen gosu process on window close

### ISSUE THREAD

**Issue by jwoertink** [gosu/gosu#139]
With a simple game, hitting the Gosu::KbEscape and calling window.close will close the window, but not kill the process. After closing the game, I have to Ctrl+C in the terminal to fully quit the application. 

I'm running Ruby 1.9.3 on Mountain Lion.

``` text
1.9.3p194 :001 > RUBY_PLATFORM
 => "x86_64-darwin10.8.0" 
```

I don't think there's actually any errors, unless there's a way to turn on some sort of debugging or logging?

**Comment by lonelylittlelucas** [comment]
I seem to be having the same problem, but without music

Any insight?

**Comment by jlnr** [comment]
@lonelylittlelucas On which exact operating system, and with which version of Ruby and Gosu? Do you have a minimal example?

**Comment by lonelylittlelucas** [comment]
i am using Windows, and ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32] and gosu (0.14.5 x64-mingw32)
i am making my display with the superclass of Gosu::Window
in my window object, have an instance variable `@window` which contains the logic for the current screen i am displaying.
i can call the `draw` and `update` methods in the `draw` and `update` of the actual window
```ruby
class Window < Gosu::Window
    def initialize
        @window=Main_Menu.new(self) #stores the window as @parent
    end
    #draw and update
    def button_down(id)
        case id
        #simple button logic
        end
    end
    def end()
        self.close
    end
end
```
then, when i try to call `@parent.end()` in any class i put into `@window` it inconsistently has the issue.
i have deduced this to the `button_down` method, as when i use only the down arrow to navigate my menu to `Exit` the error happens less than usual, but when i press the up arrow, the error happens more often.

I tried to add as much as i can, I hope you can find an issue

**Comment by lonelylittlelucas** [comment]
simmalar to #500, this only happens with fullscreen
maybe calling window.close in fullscreen is broken?

**Comment by jlnr** [comment]
@lonelylittlelucas Have you tried running other OpenGL games such as Super Tux Kart? I can only handle bugs when other OpenGL-based games work fine on the same machine (i.e. the problem is within Gosu).
