### ISSUE TITLE
Gosu does not pick up Comic Sans TTF on Windows

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#154]
If Quit passes in "C:/Windows/Fonts/comic.ttf" as the filename to `Gosu::Font.new`, the resulting font is Arial (fallback).

**Comment by Dahrkael** [comment]
Just tried this on Windows 10 x64 with ruby 2.2 and gosu 0.10.8.
It works as it should using 
```
@font = Gosu::Font.new(fontsize, {:name => "C:/Windows/Fonts/comic.ttf"})
![wizardzarial](https://cloud.githubusercontent.com/assets/115669/20787901/8915e938-b7ae-11e6-80ea-7083b52ff321.png)
![wizardzcomic](https://cloud.githubusercontent.com/assets/115669/20787902/89191fae-b7ae-11e6-85b5-4e51856207d5.png)

**Comment by jlnr** [comment]
Bad luck @Quit, I'm closing this! Thanks for the re-test, Dahrkael
