### ISSUE TITLE
A playing Gosu::Song prevents the Ruby/Gosu process from terminating

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#161]
See http://www.libgosu.org/cgi-bin/mwf/topic_show.pl?tid=838

**Comment by rubyFeedback** [comment]
Hmm. Just a remark, feel free to ignore this. at_exit is a cool feature,
I use it in some scripts. In my own libraries, though, I tend to avoid
it because it is hard(er) to control various at_exit events.

**Comment by jlnr** [comment]
Yep, I've already started to remove all atexits from the C++ code because it's really tricky to clean up stuff in the right order in a Ruby C extension :+1:
