### ISSUE TITLE
Fix make warnings

### ISSUE THREAD

**Issue by Lowest0ne** [gosu/gosu#197]
Is there any demand for having the signed/unsigned and depreciated warnings fixed?  I'm fixing them now, and figure I would put the fixes into the same PR ( provided everything goes well ).

Hmm, maybe I get the depreciated warnings because I can compile with c++11?

**Comment by jlnr** [comment]
There is no separate C++11 mode anymore.

I'm trying to fix the remaining warnings as I go along and clean up the codebase. A catch-all ticket is not helpful because new warnings pop up all the time.

Closing this ticket, but PRs for fixed warnings are welcome.
