### ISSUE TITLE
Clearer installation instructions on the home page

### ISSUE THREAD

**Issue by RavensKrag** [gosu/gosu#215]
**Add links on the libgosu.org page to the detailed install instructions for OSX, Linux, and Raspberry Pi**

I'm hoping this will make installation of Gosu easier for both veterans and noobies.
(side benefit: shows off what platforms Gosu runs on)

---

The installation instructions on the main page just say to run `gem install gosu`, with a small blurb for OSX considerations.

I assume this is good enough for Windows users, because there's a pre-compiled binary. But it's not sufficient for Linux.

I understand that the error message you get when the gem fails to install links to the wiki. However, the experience of having to go through a failure before you can install Gosu is awkward at best. Especially considering that OSX has "special" considerations, and now we have Raspberry Pi as well, it seems like Windows is actually the special case now.

**Comment by jlnr** [comment]
Homepage links to OS X and Linux build instructions now
