### ISSUE TITLE
Gosu::Song playback issues

### ISSUE THREAD

**Issue by jangler** [gosu/gosu#224]
`Gosu::Song.new(self, 'res/music.ogg').play(true)`

when using ogg files, music eventually stops for no apparent reason. when using wav or flac files, music just... sounds awful. nasty noises.

using:
- gosu 0.7.50
- ruby 2.1.2
- libsndfile 1.0.25
- openal 1.15.1
- (arch) linux 3.14.4

results are identical regardless of whether using pulseaudio on top of alsa or not. see my repository [pong-gosu](https://github.com/jangler/pong-gosu) for the code i'm using.

__edit:__ seems i can work around this issue by using a `Gosu::Sample` instead. this works fine for ogg files, but wav and flac files alternate between ~1 second of playback and ~1 second of silence.

**Comment by jlnr** [comment]
Nasty noises should have been fixed as part of #237. The OGG looping bug may or may not have been fixed by switching to stb_vorbis.

I'll optimistically close this. If things are still broken on Arch, I can give you a few pointers on how to debug this.

**Comment by rubyFeedback** [comment]
I am also trying .ogg files recently; when using .stop on a Gosu::Song instance
I have odd "background" noise as if something is still playing.

I am not using pulseaudio though, but it seems as if Gosu::Song may indirectly
try for pulse output? Anyway, my comment is not that useful, I am aware of it.

I will try to be more systematic eventually, perhaps even try to discover differences
I can find. I am not a ruby noob, but I am still a gosu-noob as I write this. :)
