### ISSUE TITLE
Playing a WAV file as `Gosu::Song` does not work

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#237]
Not sure if this is a Windows-only bug. Maybe only OGG songs work, and no-one has ever used one of the `libsndfile` formats?! Wow.

`song.reset(new Gosu::Song(L"C:/Windows/Media/Windows Startup.wav"));` -> stuttering

**Comment by AJFaraday** [comment]
I'm getting the same problem with XUbuntu 14.4

**Comment by Monster52** [comment]
Same issues with Ubuntu 14.04.  Playing it as a Gosu::Sample works but cuts in and out and just crazy noise if played as Gosu::Song

**Comment by jlnr** [comment]
Might be a bug in my `SndFile.hpp` implementation. :| Maybe I should do as the SFML does, and drop support for most variants of WAV files, and only support PCM files - looks simple enough:

https://github.com/SFML/SFML/blob/master/src/SFML/Audio/SoundFileReaderWav.cpp#L268

**Comment by AJFaraday** [comment]
In all honesty, I don't really see a problem de-supporting .wav, or specific forms of wav, if it's clear what is supported and what is not. E.G. if we had a message along the lines of ".wav files can not be supported", or ".wav files must be 16 bit Windows PCM format", instead of just having mashed audio.

**Comment by jlnr** [comment]
Good point about the error message. Early versions of Gosu used to choke on some exotic variations of the PNG file format, and it confused users for years because one in a dozen PNG files would suddenly look wrong.

I don't think dropping WAV altogether is realistic, but limiting it to PCM would definitely do the trick.

Anyway, I'll look into the SndFile.h bug now, maybe it's obvious once I actually open the file :)

**Comment by jlnr** [comment]
Sigh, fixed in https://github.com/gosu/gosu/commit/169ddcaa0494ec1fbbaa5748176ef72490c5c2e3

All caused by my failure to RTFM...
