### ISSUE TITLE
Mac: Inconsistent fullscreen behaviour in (some?) multi-monitor setups

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#245]
`Gosu::screen_width`, the new `Gosu::available_width` and `Gosu::Window`'s default position should all use the default screen.

In a quick test with SDL 2.0.3 and SDL HEAD (as of today), `[NSScreen screens][0]` and `SDL_GetDisplayMode(..., 0, ...)` both refer to my laptop's built-in screen. However fullscreen windows (and only fullscreen windows!) are shown as a space on my external screen. This shouldn't happen - everything should either refer to screen 0, or the `CGMainDisplayID` or whatever.

This might be an SDL bug, actually. Gosu uses `SDL_WINDOWPOS_CENTERED` =  `SDL_WINDOWPOS_CENTERED_DISPLAY(0)`, which should not create a window on display 1 (external screen).

**Comment by Juksefantomet** [comment]
Just a thought here, not sure what windows OS you're using, but i found myself beeing puzzled by a similar situation with later releases of windows. 

as you're using available width --> when taking a simple screenshot in windows now it actually captures both screens as default on screenshots - does this mean your available_width simply ignores display id and snaps into the entire width of both screens?

**Comment by jlnr** [comment]
I'm not sure if I understand – `available_width` should return the width of the primary display minus any vertical bars (if you moved the start menu to the left or right side of the screen). Does it not do this?

**Comment by jlnr** [comment]
This has been fixed and merged into master in #459.
