### ISSUE TITLE
Unable to install Gosu on Mac OSX 10.9.5

### ISSUE THREAD

**Issue by yzhao2012** [gosu/gosu#253]
Hi All,

I've been using gosu v0.7.48 for a while on ruby 1.9.3-p448. Recently, I tried to install gosu on my friends computer, but I ran into the following error:
# 

The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/jlnr/gosu/wiki/Getting-Started-on-OS-X

creating Makefile

make
compiling gosu_wrap.cxx
gosu_wrap.cxx:851:10: fatal error: 'map' file not found
# include <map>

```
     ^
```

1 error generated.
make: **\* [gosu_wrap.o] Error 1
# 

I've installed all the prerequired libraries on their computer, and they also have command line tools installed (version 2333). I then tried to upgrade gosu on my own computer that had it previously installed and it came up with the same error. Is there a reason that it's not reading the c++ file properly? I'd be really great if someone could help me understand:
1) What the above situation means, and 
2) How to fix it.

Thanks!

**Comment by yzhao2012** [comment]
I know you closed this, but rbenv worked wonders.

**Comment by jlnr** [comment]
Phew! :+1:

**Comment by DanielVF** [comment]
Oddly enough I was having a similar error on ruby 1.9.3-p545, with rbenv. Switching to using Ruby 2.1.1, still under rbenv, fixed it.
