### ISSUE TITLE
OS X installation fails

### ISSUE THREAD

**Issue by iamjoshua** [gosu/gosu#256]
The https://github.com/jlnr/gosu/wiki/Getting-Started-on-OS-X guide didn't seem to get me started.

I'm running the latest versions of Yosemite, xcode and command line tools, but after running

```
brew install sdl2 libogg libvorbis
```

and

```
sudo gem install gosu
```

I'm running into the following error:

```
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
```

Is there something I'm missing?

**Comment by mpapis** [comment]
for anyone else hitting this problem - **do not** mix `rvm` and `sudo` - as `sudo` resets environment which is equal to not using `rvm`

**Comment by andrewhavens** [comment]
There's the rvmsudo command for when you really need to use sudo.



-- Andrew Havens
