### ISSUE TITLE
SampleInstance#position= or Song#seek

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#264]
Suggested by @shawn42 - would be nice to jump into a song, and I think it would only be consistent if you could also read back its position.

**Comment by shawn42** [comment]
Requested for @squarism

**Comment by jlnr** [comment]
It's been a while. @shawn42 do you still know what the use case for this was? I've mostly decided against adding this in https://github.com/gosu/gosu/pull/504#pullrequestreview-406191563.

**Comment by squarism** [comment]
@shawn42 could probably fill in the details but I was using a library to play a very long sample (a song versus a one shot sound effect).

I thought I'd throw something else out there.  I'm noticing some tools adding extra markers and headers to .wav files.  In some use cases, it's kind of like sections, or keyframes.  I'm not completely sure it applies here.  If you want an example file, maybe I could make one for you.  But only if you are curious.

Btw, the project I was working on has wrapped up (so, how important is it really?).  It was recorded a while back, music video tech talk.  A fun time.  👋 to @shawn42 😄 .  If it's blocking, I might not worry about it.

**Comment by shawn42** [comment]
I can't for the life of me remember why I wanted this.  I say nix it til a use case presents itself.

**Comment by jlnr** [comment]
@squarism Working with key frames would be awesome. When Gosu still used DirectX I remember that [Microsoft had a whole API for that](https://en.wikipedia.org/wiki/DirectMusic#Details), and I always wanted to give it a try. Using something like that for a tech talk sounds good as well!

Anyway, I don't have much tinkering time right now and would like to keep new features to the absolute minimum. I'm going to close this and other feature requests for now. For any new project it would probably be best to discuss what would be needed on Discord; maybe it's actually easier to use something like FMOD in addition to Gosu, I've never tried.
