### ISSUE TITLE
Ship C libraries with gem

### ISSUE THREAD

**Issue by v0dro** [gosu/gosu#274]
I'm trying to use gosu on a Raspberry Pi and its becoming a hell of task to install all the libraries, since a few (like libsdl2-dev) aren't available from the official Raspbian repositories.

It would be great if you could ship the dependencies with gosu and compile them from source if they are not already present on the user's machine.

**Comment by jlnr** [comment]
Bundling all the SDL libraries with Gosu *and* integrating them into the extconf script would be quite brutal. I think it would be simpler to set up a shell script that executes all the steps from this guide, what do you think?

https://github.com/jlnr/gosu/wiki/Getting-Started-on-Raspbian-%28Raspberry-Pi%29

That would definitely be easier to debug :)

**Comment by andrewhavens** [comment]
:+1: Shell script auto-installer would be nice!

**Comment by v0dro** [comment]
I hadn't noticed that wiki page. Thanks! 

And yes an auto install would be great.

**Comment by jlnr** [comment]
I'm closing this issue as bundling libsdl2 with Gosu is not feasible.
