### ISSUE TITLE
Mouse key hangs when dragging window

### ISSUE THREAD

**Issue by Aerotune** [gosu/gosu#275]
When you drag a window in the top menu bar you get a button_down Gosu::MsLeft  but not a button_up Gosu::MsLeft before you click inside the window again. The key also hangs when checking with button_down? Gosu::MsLeft.

I'm using Mac OS Yosemite and gosu (0.8.7.2)

**Comment by jlnr** [comment]
Yep, I can reproduce this even with `brew install sdl2 --HEAD`.

Since I don't receive `SDL_KEYUP` or `SDL_KEYDOWN` events inside of Gosu, this looks like an SDL bug to me. I'll leave this ticket open as a reminder for myself (or anyone who's interested) to file an SDL issue for this.

**Comment by jlnr** [comment]
I cannot reproduce this on El Capitan with SDL 2.0.5.
