### ISSUE TITLE
Could not create window: GLX is not supported

### ISSUE THREAD

**Issue by ashes999** [gosu/gosu#282]
Hi,

I'm trying to run Gosu in an Ubuntu 12.04 VM. I've followed all the setup instructions to get the core packages through `apt`, and SDL, and installed the gem successfully.

Here's the full stack trace:

```
/gems/ruby-2.2.1/gems/gosu-0.9.2/lib/gosu/swig_patches.rb:19:in `initialize': Could not create window: GLX is not supported (RuntimeError)
	from /home/ashiq/.rvm/gems/ruby-2.2.1/gems/gosu-0.9.2/lib/gosu/swig_patches.rb:19:in `initialize'
	from main.rb:15:in `initialize'
	from main.rb:33:in `new'
	from main.rb:33:in `<main>'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not create window: GLX is not supported
Aborted (core dumped)
```

Relevant lines from Main.rb:

```
class GameWindow < Gosu::Window

  def initialize
    super(800, 600,false) # <== crashes here
    # ...
  end
end
```

Is there a solution or work-around for this?

Also, the wiki page suggested installing apt packages for `libsdl2-dev` and `libsdl2-ttf-dev`, but neither exists in the 12.04 repositories.  Is compiling SDL (as described later in the setup guide) sufficient?

**Comment by jlnr** [comment]
Yes and no. You can compile SDL 2 yourself, but then you have to take care that it supports OpenGL/GLX. It shouldn't matter whether your VM supports OpenGL hardware acceleration or not, since OpenGL can be emulated in software, but it's something to keep in mind.

If I had to give it a try as a Linux graphics n00b, I'd probably try to install a few mesa gl packages, and then running `./configure` from the SDL 2 source code to see if it says anything about GL.

Is there any way for you to upgrade to Ubuntu 14.04+?

**Comment by ashes999** [comment]
How did you know I'm a Linux graphics noob? :)

Upgrading to 14.04 is out of the question, unfortunately -- I had to reinstall 12.04 because of a GPU driver bug that caused very frequent tearing.

I ran `./configure | grep GL` and I get `checking for OpenGL (GLX) support... yes`. That makes me suspicious that it should work.

I just found packages for `libsdl1.2-dev` and `libsdl-ttf2.0-dev` which I installed, but I still get the same error. 

1) Is it because my pre-built versions are now used instead of the ones from `apt`?  What now?
2) Should I update the wiki page with the updated package names?

**Comment by jlnr** [comment]
Oops - should have been "if I, a Linux graphics n00b, had to give it a try"... :)

Gosu is not compatible with SDL 1.2, only 2.0+, so the packages won't work.

Do other OpenGL apps/games work in your VM?

**Comment by ashes999** [comment]
I'm not sure.

I'll try upgrading to 14.04 again and see if that's stable. I already verified that the installation of Gosu is trivial on 14.04.

I would suggest not supporting 12.04, if it's this difficult to get a working configuration :(

**Comment by jlnr** [comment]
There is no such thing as supported and unsupported with Gosu on Linux. But I'm trying to push all the responsibility for working on the OS level down to the libsdl2 dependency. If there is no SDL 2 package (such as in Raspbian) you know you're in for trouble :)

**Comment by ashes999** [comment]
I don't know what the solution is for this. I upgraded to 14.04 and it works.

**Comment by jlnr** [comment]
Good to hear :)

**Comment by rubyFeedback** [comment]
I ran into a similar problem recently. Not sure how to fix it yet with SDL2.

https://www.linuxfromscratch.org/blfs/view/svn/multimedia/sdl2.html

Does not mention any special build flag to be used.
