### ISSUE TITLE
Callback when closing the window via [x]

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#287]
Since all platforms use SDL 2 now, this should be either trivial to implement - or impossible - but nothing in-between. ;)

First idea for the interface:

``` ruby
class Gosu::Window
  ...
  def try_close
    close # feel free to override this and do something else instead
  end
  ...
end
```

I'm not really happy with `try_close` though =/

**Comment by RavensKrag** [comment]
Perhaps call it `on_close` or `on_shutdown`? Also, I don't think it should be necessary to call `close` from inside that callback. The window should always close after hitting the [x], and you should just modify what happens right before closure. (but maybe you just included the `close` inside that block for illustrative purposes?)

On Linux there are other ways to close a window than using the [x] button. I wonder if they all would trigger the same callback.

Regardless, this is something I've hacked together in my projects for some time now, and would certainly appreciate it. Good luck :D

**Comment by jlnr** [comment]
I don't like the `on_` prefix because Gosu has not used it at all so far =/ Maybe something like `close_requested`? Hmm.

In any case, I thought the point of this feature was to be able to add confirmation dialogs in Gosu apps, but maybe I misunderstood:

![bildschirmfoto 2015-08-02 um 11 55 33](https://cloud.githubusercontent.com/assets/70772/9025646/8f735372-390d-11e5-969d-ac91f7500b27.png)

In that case the `close` cannot be implicit. If you only want to run code after the window has been closed, you can either add it below `window.show`, or override `Window#show` and call `super`, then your own clean-up code.

**Comment by RavensKrag** [comment]
I can see how creating something like a "do you want to save?" dialog would require intercepting the `close`. I wasn't thinking about that case, and had not seen the forum post before commenting on this issue. I was speaking only about my own desires, and I apologize.

(for reference, that thread is [here](https://www.libgosu.org/cgi-bin/mwf/topic_show.pl?tid=1203))

However, if you program a callback into `close` by overwriting `close`, why would you need to call the original? Would this not mean that you want some code to execute any time the window is closed, by any means? If you really absolutely need to do this is ruby, you can preserve the original method by using `alias`. But as far as I understand Ruby's methodology, you shouldn't be calling the old method in most cases.

**Comment by jlnr** [comment]
Sorry for not linking to the thread before, and thanks for adding the link :)

I was thinking of this:

```ruby
class Window < Gosu::Window
  ...
  alias :original_close :close
  def close
    @close_confirmation = true
  end
  ...
  def button_down(id)
    original_close if @close_confirmation and button_id_to_char(id) == 'Y'
  end
end
```

So basically, `Window#close` would be both the callback, and the method that closes the window. But that's a terrible way of avoiding to come up with a new method name ^^"

**Comment by Dahrkael** [comment]
why not Window#closing ? since the action is already happening when the method gets called.
for the ruby side, can't this be replicated using the pair begin/ensure?

**Comment by runnerpack** [comment]
I've had a few more thoughts on this: https://www.libgosu.org/cgi-bin/mwf/topic_show.pl?pid=8698#pid8698

**Comment by jlnr** [comment]
Thanks for your input. I prefer methods that end in `?` to be free of side effects, so I'm not sure about `close?`. What about the other way, using `!` for the method that really closes the window (pseudocode):

```ruby
class MyWindow < Gosu::Window
  # Override #close which will be called when the user wants to exit
  # By default, Gosu::Window#close just calls #close! (see below)
  def close
    self.caption = "Really exit? Confirm with F6"
    @closing = true
  end

  def button_down(id)
    close if id == Gosu::KB_ESCAPE
    # Gosu::Window#close! would be a new method that closes the window without any chance to interrupt
    close! if id == Gosu::KB_F6 and @closing
  end
end
```

**Comment by runnerpack** [comment]
Even though I don't know what you mean by "side effects", I like your idea. Stopping the entire program definitely counts as "dangerous" enough to warrant the "bang" :smiley:

**Comment by Kjarrigan** [comment]
Every once in a while i look through the "old" issues and this is definitely one. I'm in favor of =close!=, so why not do it that way and finish this issue :smile:

**Comment by jlnr** [comment]
Well, feel free to open another PR - I am busy catching up with client work for the rest of the working week :( It *should* be a simple fix!

**Comment by Kjarrigan** [comment]
Ok no problem, I'll look into it.

**Comment by Kjarrigan** [comment]
Well - it actually is a problem. I guess I don't know enough about Gosu internals, C++ and SWIG to make this work in clean way... I mainly got a the following problems I can't resolve so far:

At the moment you call _close_ from Ruby which calls _close__ in C++ which registers a QUIT event which eventually will be processed by _Window::tick_. Now we want to change this behavior, so that _Window::tick_ calls __close__ when it receives an QUIT event which:

1. breaks the c++ API as we need an replacement for C++ to register the event. (e.g. quit)
2. should call the ruby close method but obviously not in the c++ version of Gosu and I have no clue how to do that. _rb_func_call_ should be the way to go but where to put that.

So you probably have to do it yourself, as you seem to have an idea how to do this. I guess a couple more days or weeks "delay" would be no problem as this ticket is open for a more than a year now. But I'll try to think about this a bit more as this could be a good way to learn more about the internals and SWIG :smile: and C(++)-ruby-bindings
