### ISSUE TITLE
Ruby Tutorial did not work for me

### ISSUE THREAD

**Issue by jdell64** [gosu/gosu#289]
Star::draw has a div by zero error. (@animation.size =0) 

    C:/dev/gosu/tutorial.rb:80:in `draw': divided by 0 (ZeroDivisionError)
        from C:/dev/gosu/tutorial.rb:124:in `block in draw'
        from C:/dev/gosu/tutorial.rb:124:in `each'
        from C:/dev/gosu/tutorial.rb:124:in `draw'
        from C:/dev/gosu/tutorial.rb:129:in `<top (required)>'
        from -e:1:in `load'
        from -e:1:in `<main>'

Also, if I change img just to get past the divided by 0 error to something like this:

    img = @animation[Gosu::milliseconds / 100 % 1];

I get this:

    C:/dev/gosu/tutorial.rb:83:in `draw': undefined method `width' for nil:NilClass (NoMethodError)
        from C:/dev/gosu/tutorial.rb:126:in `block in draw'
        from C:/dev/gosu/tutorial.rb:126:in `each'
        from C:/dev/gosu/tutorial.rb:126:in `draw'
        from C:/dev/gosu/tutorial.rb:131:in `<top (required)>'
        from -e:1:in `load'
        from -e:1:in `<main>'

**Comment by jdell64** [comment]
I was able to get it to work with this, but it does cut out animation:

    def initialize(animation)
        @animation = animation
        @color = Gosu::Color.new(0xff_000000)
        @color.red = rand(256 - 40) + 40
        @color.green = rand(256 - 40) + 40
        @color.blue = rand(256 - 40) + 40
        @x = rand * 640
        @y = rand * 480
        @image = Gosu::Image.new("media/star.png")
      end
    
    def draw
        @image.draw(@x, @y, ZOrder::Stars)
    end

**Comment by jlnr** [comment]
That's odd, what size is `star.png`? It makes sense that the array would be empty if the width or height is < 25 - `load_tiles` would return an empty array in that case.

Does `gem install gosu-examples`, then running `gosu-examples` work for you? It contains the tutorial and works here. I use it to test Gosu all the time.

**Comment by jdell64** [comment]
You know what... I didn't download the example code / files. I made my own
pngs and classes. I thought it might cut the file into frames or something,
but I couldn't find the RDocs.

You can close my issue. Thanks!

On Wednesday, August 12, 2015, Julian Raschke <notifications@github.com>
wrote:

> That's odd, what size is star.png? It makes sense that the array would be
> empty if the width or height is < 25 - load_tiles would return an empty
> array in that case.
>
> Does gem install gosu-examples, then running gosu-examples work for you?
> It contains the tutorial and works here. I use it to test Gosu all the time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gosu/gosu/issues/289#issuecomment-130461416>.
>


-- 

--
Richard J Tindell

Ps 102:18- "This will be written for the generation to come, That a people
yet to be created may praise the Lord."

**Comment by jlnr** [comment]
I see :) I should probably link to all the assets in the `gosu-examples` repository inside the Ruby Tutorial wiki page. I'll leave this issue open as a reminder.

**Comment by jlnr** [comment]
Done. Thanks for the feedback! It's always good to know what might go wrong in the tutorial (which still isn't as straightforward as I wish it was).
