### ISSUE TITLE
0.10.x has broken gem install gosu

### ISSUE THREAD

**Issue by wurde** [gosu/gosu#291]
On trying to upgrade gosu to latest 0.10.x I can't because of following error: 

    Makefile:229: recipe for target 'Bitmap-BitmapIO.o' failed
    make: *** [Bitmap-BitmapIO.o] Error 1
    make failed, exit code 2

Ubuntu 15.04
Ruby 2.2.2p95 (2015-04-13 revision 50295) [i686-linux]

**Comment by wurde** [comment]
gosu-0.9.2 installs fine.

**Comment by jlnr** [comment]
Gosu needs better QA... Thanks for reporting this, I've pushed a new version that should fix the issue (0.10.1.1).

**Comment by wurde** [comment]
Agreed and thank you.
