### ISSUE TITLE
Error when loading ogg file in latest ruby gem

### ISSUE THREAD

**Issue by lepolepo** [gosu/gosu#295]
I just updated to the latest ruby gem and an error is thrown when I call Gosu::Song.new("somefile.ogg"): <br>"ruby: symbol lookup error: ~/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/gosu-0.10.1.1/gosu.so: undefined symbol: stb_vorbis_open_memory". <br>Everything works fine with 0.9.2 and in 0.10.1 with C++. So, the problem might have to do with how the ruby extension is built after the new audio changes. I'm using the latest Arch Linux x86_64 and MRI Ruby 2.2.3 (latest).

**Comment by jlnr** [comment]
Yep, that was exactly the issue. Sorry, the 0.10.x series has been quite a mess so far! I've pushed a fix as version 0.10.1.2.
