### ISSUE TITLE
Can't compile gosu 0.10.1.2 on Ubuntu 15.04 (vivid)

### ISSUE THREAD

**Issue by aanno** [gosu/gosu#298]
I can't compile (i.e. update the gem). The problem has not existed with gosu 0.9.2 which still compiles fine.

Cheers,

aanno

> gem update gosu  
Updating installed gems
Updating gosu
Building native extensions.  This could take a while...
ERROR:  Error installing gosu:
        ERROR: Failed to build gem native extension.

    /opt/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150904-9412-l8huyi.rb extconf.rb
The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/jlnr/gosu/wiki/Getting-Started-on-Linux

checking for TTF_RenderUTF8_Blended() in -lSDL2_ttf... yes
checking for SDL_ttf.h... yes
checking for main() in -lopenal... yes
checking for AL/al.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling stb_vorbis.c
In file included from stb_vorbis.c:1:0:
../../src/stb_vorbis.c: In function ‘start_decoder.part.19’:
../../src/stb_vorbis.c:3956:32: warning: ‘hi’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             g->neighbors[j][1] = hi;
                                ^
../../src/stb_vorbis.c:3955:32: warning: ‘low’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             g->neighbors[j][0] = low;
                                ^
compiling gosu_wrap.cxx
gosu_wrap.cxx: In function ‘VALUE _wrap_Font_draw_rot(int, VALUE*, VALUE)’:
gosu_wrap.cxx:5447:111: warning: ‘void Gosu::Font::drawRot(const wstring&, double, double, Gosu::ZPos, double, double, double, Gosu::Color, Gosu::AlphaMode) const’ is deprecated (declared at ../../Gosu/Font.hpp:81) [-Wdeprecated-declarations]
       ((Gosu::Font const *)arg1)->drawRot((std::wstring const &)*arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
                                                                                                               ^
compiling Bitmap-Bitmap.cpp
compiling Bitmap-BitmapIO.cpp
In file included from Bitmap-BitmapIO.cpp:1:0:
../../src/Bitmap/BitmapIO.cpp: In function ‘Gosu::Reader Gosu::loadFromBMP(Gosu::Bitmap&, Gosu::Reader)’:
../../src/Bitmap/BitmapIO.cpp:146:12: warning: ‘Gosu::Reader Gosu::loadFromPNG(Gosu::Bitmap&, Gosu::Reader)’ is deprecated (declared at ../../src/Bitmap/BitmapIO.cpp:137) [-Wdeprecated-declarations]
     return loadFromPNG(bitmap, reader);
            ^
../../src/Bitmap/BitmapIO.cpp:146:38: warning: ‘Gosu::Reader Gosu::loadFromPNG(Gosu::Bitmap&, Gosu::Reader)’ is deprecated (declared at ../../src/Bitmap/BitmapIO.cpp:137) [-Wdeprecated-declarations]
     return loadFromPNG(bitmap, reader);
                                      ^
compiling DirectoriesUnix.cpp
compiling FileUnix.cpp
compiling Graphics-BlockAllocator.cpp
compiling Graphics-Color.cpp
compiling Graphics-Graphics.cpp
compiling Graphics-Image.cpp
compiling Graphics-LargeImageData.cpp
compiling Graphics-Macro.cpp
compiling Graphics-Resolution.cpp
In file included from Graphics-Resolution.cpp:1:0:
../../src/Graphics/Resolution.cpp:53:5: error: ‘SDL_DisplayMode’ does not name a type
     SDL_DisplayMode currentDisplayMode = { 0, 0 };
     ^
../../src/Graphics/Resolution.cpp: In function ‘unsigned int Gosu::screenWidth()’:
../../src/Graphics/Resolution.cpp:59:9: error: ‘currentDisplayMode’ was not declared in this scope
     if (currentDisplayMode.w == 0) {
         ^
../../src/Graphics/Resolution.cpp:61:53: error: ‘SDL_GetDisplayMode’ was not declared in this scope
         SDL_GetDisplayMode(0, 0, &currentDisplayMode);
                                                     ^
../../src/Graphics/Resolution.cpp:64:12: error: ‘currentDisplayMode’ was not declared in this scope
     return currentDisplayMode.w;
            ^
../../src/Graphics/Resolution.cpp: In function ‘unsigned int Gosu::screenHeight()’:
../../src/Graphics/Resolution.cpp:70:9: error: ‘currentDisplayMode’ was not declared in this scope
     if (currentDisplayMode.h == 0) {
         ^
../../src/Graphics/Resolution.cpp:72:53: error: ‘SDL_GetDisplayMode’ was not declared in this scope
         SDL_GetDisplayMode(0, 0, &currentDisplayMode);
                                                     ^
../../src/Graphics/Resolution.cpp:75:12: error: ‘currentDisplayMode’ was not declared in this scope
     return currentDisplayMode.h;
            ^
Makefile:229: recipe for target 'Graphics-Resolution.o' failed
make: *** [Graphics-Resolution.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/gosu-0.10.1.2 for inspection.
Results logged to /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/gosu-0.10.1.2/gem_make.out
Gems updated: gosu

**Comment by jlnr** [comment]
That's odd. I have changed the way Gosu includes the SDL headers in v0.10.0, but the compiler can apparently find `SDL.h`. Maybe it's finding the wrong SDL.h (version 1.x, perhaps)?
Can you please post the output of:
```bash
pkg-config sdl2 --cflags
```

**Comment by aanno** [comment]
$ pkg-config sdl2 --cflags
-D_REENTRANT -I/usr/include/SDL2

Makefile from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/gosu-0.10.1.2/ext/gosu:
<pre>

SHELL = /bin/sh

# V=0 quiet, V=1 verbose.  other values don't work.
V = 0
Q1 = $(V:1=)
Q = $(Q1:0=@)
ECHO1 = $(V:1=@:)
ECHO = $(ECHO1:0=@echo)
NULLCMD = :

#### Start of system configuration section. ####

srcdir = .
topdir = /opt/rubies/ruby-2.2.2/include/ruby-2.2.0
hdrdir = $(topdir)
arch_hdrdir = /opt/rubies/ruby-2.2.2/include/ruby-2.2.0/x86_64-linux
PATH_SEPARATOR = :
VPATH = $(srcdir):$(arch_hdrdir)/ruby:$(hdrdir)/ruby
prefix = $(DESTDIR)/opt/rubies/ruby-2.2.2
rubysitearchprefix = $(rubylibprefix)/$(sitearch)
rubyarchprefix = $(rubylibprefix)/$(arch)
rubylibprefix = $(libdir)/$(RUBY_BASE_NAME)
exec_prefix = $(prefix)
vendorarchhdrdir = $(vendorhdrdir)/$(sitearch)
sitearchhdrdir = $(sitehdrdir)/$(sitearch)
rubyarchhdrdir = $(rubyhdrdir)/$(arch)
vendorhdrdir = $(rubyhdrdir)/vendor_ruby
sitehdrdir = $(rubyhdrdir)/site_ruby
rubyhdrdir = $(includedir)/$(RUBY_VERSION_NAME)
vendorarchdir = $(vendorlibdir)/$(sitearch)
vendorlibdir = $(vendordir)/$(ruby_version)
vendordir = $(rubylibprefix)/vendor_ruby
sitearchdir = $(DESTDIR)./.gem.20150904-9412-z3cy47
sitelibdir = $(DESTDIR)./.gem.20150904-9412-z3cy47
sitedir = $(rubylibprefix)/site_ruby
rubyarchdir = $(rubylibdir)/$(arch)
rubylibdir = $(rubylibprefix)/$(ruby_version)
sitearchincludedir = $(includedir)/$(sitearch)
archincludedir = $(includedir)/$(arch)
sitearchlibdir = $(libdir)/$(sitearch)
archlibdir = $(libdir)/$(arch)
ridir = $(datarootdir)/$(RI_BASE_NAME)
mandir = $(datarootdir)/man
localedir = $(datarootdir)/locale
libdir = $(exec_prefix)/lib
psdir = $(docdir)
pdfdir = $(docdir)
dvidir = $(docdir)
htmldir = $(docdir)
infodir = $(datarootdir)/info
docdir = $(datarootdir)/doc/$(PACKAGE)
oldincludedir = $(DESTDIR)/usr/include
includedir = $(prefix)/include
localstatedir = $(prefix)/var
sharedstatedir = $(prefix)/com
sysconfdir = $(prefix)/etc
datadir = $(datarootdir)
datarootdir = $(prefix)/share
libexecdir = $(exec_prefix)/libexec
sbindir = $(exec_prefix)/sbin
bindir = $(exec_prefix)/bin
archdir = $(rubyarchdir)


CC = gcc
CXX = g++
LIBRUBY = $(LIBRUBY_A)
LIBRUBY_A = lib$(RUBY_SO_NAME)-static.a
LIBRUBYARG_SHARED = -Wl,-R$(libdir) -L$(libdir) 
LIBRUBYARG_STATIC = -Wl,-R$(libdir) -L$(libdir) -l$(RUBY_SO_NAME)-static
empty =
OUTFLAG = -o $(empty)
COUTFLAG = -o $(empty)

RUBY_EXTCONF_H = 
cflags   =  $(optflags) $(debugflags) $(warnflags)
optflags = -O3 -fno-fast-math
debugflags = -ggdb3
warnflags = -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat
CCDLFLAGS = -fPIC
CFLAGS   = $(CCDLFLAGS) $(cflags) -DGOSU_DEPRECATED=  -D_REENTRANT -pthread    $(ARCH_FLAG)
INCFLAGS = -I. -I$(arch_hdrdir) -I$(hdrdir)/ruby/backward -I$(hdrdir) -I$(srcdir) -I../.. -I../../src -I/usr/include/libdrm -I/usr/include/SDL2 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2  -I/usr/include/AL 
DEFS     = 
CPPFLAGS = -DHAVE_SDL_TTF_H -DHAVE_AL_AL_H  $(DEFS) $(cppflags)
CXXFLAGS = $(CCDLFLAGS) $(cxxflags)  -D_REENTRANT -pthread    $(ARCH_FLAG)
ldflags  = -L. -fstack-protector -rdynamic -Wl,-export-dynamic      
dldflags =  
ARCH_FLAG = 
DLDFLAGS = $(ldflags) $(dldflags) $(ARCH_FLAG)
LDSHARED = $(CC) -shared
LDSHAREDXX = $(CXX) -shared
AR = ar
EXEEXT = 

RUBY_INSTALL_NAME = $(RUBY_BASE_NAME)
RUBY_SO_NAME = ruby
RUBYW_INSTALL_NAME = 
RUBY_VERSION_NAME = $(RUBY_BASE_NAME)-$(ruby_version)
RUBYW_BASE_NAME = rubyw
RUBY_BASE_NAME = ruby

arch = x86_64-linux
sitearch = $(arch)
ruby_version = 2.2.0
ruby = $(bindir)/$(RUBY_BASE_NAME)
RUBY = $(ruby)
ruby_headers = $(hdrdir)/ruby.h $(hdrdir)/ruby/ruby.h $(hdrdir)/ruby/defines.h $(hdrdir)/ruby/missing.h $(hdrdir)/ruby/intern.h $(hdrdir)/ruby/st.h $(hdrdir)/ruby/subst.h $(arch_hdrdir)/ruby/config.h

RM = rm -f
RM_RF = $(RUBY) -run -e rm -- -rf
RMDIRS = rmdir --ignore-fail-on-non-empty -p
MAKEDIRS = /bin/mkdir -p
INSTALL = /usr/bin/install -c
INSTALL_PROG = $(INSTALL) -m 0755
INSTALL_DATA = $(INSTALL) -m 644
COPY = cp
TOUCH = exit >

#### End of system configuration section. ####

preload = 

libpath = . $(libdir)
LIBPATH =  -L. -L$(libdir) -Wl,-R$(libdir)
DEFFILE = 

CLEANFILES = mkmf.log
DISTCLEANFILES = 
DISTCLEANDIRS = 

extout = 
extout_prefix = 
target_prefix = 
LOCAL_LIBS = 
LIBS =  -lopenal -lSDL2_ttf  -lGL -lSDL2 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lvorbisfile -lopenal -lsndfile -lpthread -ldl -lcrypt -lm   -lc
ORIG_SRCS = stb_vorbis.c gosu_wrap.cxx Bitmap-Bitmap.cpp Bitmap-BitmapIO.cpp DirectoriesUnix.cpp FileUnix.cpp Graphics-BlockAllocator.cpp Graphics-Color.cpp Graphics-Graphics.cpp Graphics-Image.cpp Graphics-LargeImageData.cpp Graphics-Macro.cpp Graphics-Resolution.cpp Graphics-TexChunk.cpp Graphics-Texture.cpp Graphics-Transform.cpp Input-Input.cpp Input-TextInput.cpp Inspection.cpp IO.cpp Math.cpp Text-Font.cpp Text-Text.cpp Utility.cpp Window.cpp Audio-Audio.cpp Text-TextUnix.cpp TimingUnix.cpp
SRCS = $(ORIG_SRCS) 
OBJS = stb_vorbis.o gosu_wrap.o Bitmap-Bitmap.o Bitmap-BitmapIO.o DirectoriesUnix.o FileUnix.o Graphics-BlockAllocator.o Graphics-Color.o Graphics-Graphics.o Graphics-Image.o Graphics-LargeImageData.o Graphics-Macro.o Graphics-Resolution.o Graphics-TexChunk.o Graphics-Texture.o Graphics-Transform.o Input-Input.o Input-TextInput.o Inspection.o IO.o Math.o Text-Font.o Text-Text.o Utility.o Window.o Audio-Audio.o Text-TextUnix.o TimingUnix.o
HDRS = $(srcdir)/gosu_wrap.h
TARGET = gosu
TARGET_NAME = gosu
TARGET_ENTRY = Init_$(TARGET_NAME)
DLLIB = $(TARGET).so
EXTSTATIC = 
STATIC_LIB = 

TIMESTAMP_DIR = .
BINDIR        = $(bindir)
RUBYCOMMONDIR = $(sitedir)$(target_prefix)
RUBYLIBDIR    = $(sitelibdir)$(target_prefix)
RUBYARCHDIR   = $(sitearchdir)$(target_prefix)
HDRDIR        = $(rubyhdrdir)/ruby$(target_prefix)
ARCHHDRDIR    = $(rubyhdrdir)/$(arch)/ruby$(target_prefix)

TARGET_SO     = $(DLLIB)
CLEANLIBS     = $(TARGET).so 
CLEANOBJS     = *.o  *.bak

all:    $(DLLIB)
static: $(STATIC_LIB)
.PHONY: all install static install-so install-rb
.PHONY: clean clean-so clean-static clean-rb

clean-static::
clean-rb-default::
clean-rb::
clean-so::
clean: clean-so clean-static clean-rb-default clean-rb
		-$(Q)$(RM) $(CLEANLIBS) $(CLEANOBJS) $(CLEANFILES) .*.time

distclean-rb-default::
distclean-rb::
distclean-so::
distclean-static::
distclean: clean distclean-so distclean-static distclean-rb-default distclean-rb
		-$(Q)$(RM) Makefile $(RUBY_EXTCONF_H) conftest.* mkmf.log
		-$(Q)$(RM) core ruby$(EXEEXT) *~ $(DISTCLEANFILES)
		-$(Q)$(RMDIRS) $(DISTCLEANDIRS) 2> /dev/null || true

realclean: distclean
install: install-so install-rb

install-so: $(DLLIB) $(TIMESTAMP_DIR)/.RUBYARCHDIR.time
	$(INSTALL_PROG) $(DLLIB) $(RUBYARCHDIR)
clean-static::
	-$(Q)$(RM) $(STATIC_LIB)
install-rb: pre-install-rb install-rb-default
install-rb-default: pre-install-rb-default
pre-install-rb: Makefile
pre-install-rb-default: Makefile
pre-install-rb-default:
	@$(NULLCMD)
$(TIMESTAMP_DIR)/.RUBYARCHDIR.time:
	$(Q) $(MAKEDIRS) $(@D) $(RUBYARCHDIR)
	$(Q) $(TOUCH) $@

site-install: site-install-so site-install-rb
site-install-so: install-so
site-install-rb: install-rb

.SUFFIXES: .c .m .cc .mm .cxx .cpp .o .S

.cc.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.cc.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.mm.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.mm.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.cxx.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.cxx.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.cpp.o:
	$(ECHO) compiling $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -c $<

.cpp.S:
	$(ECHO) translating $(<)
	$(Q) $(CXX) $(INCFLAGS) $(CPPFLAGS) $(CXXFLAGS) $(COUTFLAG)$@ -S $<

.c.o:
	$(ECHO) compiling $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -c $<

.c.S:
	$(ECHO) translating $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -S $<

.m.o:
	$(ECHO) compiling $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -c $<

.m.S:
	$(ECHO) translating $(<)
	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(COUTFLAG)$@ -S $<

$(DLLIB): $(OBJS) Makefile
	$(ECHO) linking shared-object $(DLLIB)
	-$(Q)$(RM) $(@)
	$(Q) $(LDSHAREDXX) -o $@ $(OBJS) $(LIBPATH) $(DLDFLAGS) $(LOCAL_LIBS) $(LIBS)



$(OBJS): $(HDRS) $(ruby_headers)
</pre>

**Comment by jlnr** [comment]
I am already on my second Ubuntu 15.04 VM, and `gem install gosu` has always worked flawlessly. `/usr/include/SDL2/SDL.h` includes `/usr/include/SDL2/SDL_video.h`, which defines `SDL_DisplayMode`.
Is there maybe another version of SDL.h available somewhere in these include paths:

`INCFLAGS = -I. -I$(arch_hdrdir) -I$(hdrdir)/ruby/backward -I$(hdrdir) -I$(srcdir) -I../.. -I../../src -I/usr/include/libdrm -I/usr/include/SDL2 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2  -I/usr/include/AL `

How did you install Ruby 2.2? I always use the standard `ruby-dev` package in Ubuntu.

**Comment by aanno** [comment]
Well, I'm (normally) using chruby _and compile ruby (and rubinius) on my own_. However, I tried to use the deb ruby (and ruby-dev) package - same result.

It seems not to be a common problem when it works for you. Perhaps there is something wrong with my installation.

But I'm not aware that I trashed the header of SDL or SDL 2 somehow. I will try to dig deeper into it when I've got the time...

**Comment by aanno** [comment]
Bummer! In ancient times, I did a link /usr/include/SDL -> /usr/include/SDL2 and haven't remembered that. 

Very sorry for the noice - it's now working flawless.

**Comment by tonmanayo** [comment]
@aanno how did you unlink this? seems I have the same problem and can't seem to solve it
