### ISSUE TITLE
Window stops displaying after a window is destroyed and replaced.

### ISSUE THREAD

**Issue by AJFaraday** [gosu/gosu#308]
This issue occurred in my lane-sim project. You can find my issue here... https://github.com/AJFaraday/lane-sim/issues/1

I am initialising new levels with a different window size by destroying one window and placing a new one. After this has happened a couple of times, I sometimes lose the window display, but my program continues to run.

Found on KDE Linux.

I can't find any error messages relating to this issue, or precisely nail down the situation where it happens.

(Alternately, if there is a way to change the height and width of an existing window, instead of destroying and replacing it, this would solve my problem)

**Comment by jlnr** [comment]
Gosu 0.10.x has been out for a while and should fix exactly this issue. If it doesn't, please let me know :)

Also, add `Window#resize` is definitely on my list! I'm just slooow.

**Comment by AJFaraday** [comment]
Changing to version 0.10.4 (distributed by rubygems.org) has fixed this issue for me. Thanks!
