### ISSUE TITLE
Manipulate Window object after sending show message

### ISSUE THREAD

**Issue by quantumpotato** [gosu/gosu#311]
```
class Game < Gosu::Window

game = Game.new
Thread.new {
  game.show
}

game.doStuff
```

This works, but my game is invisible to me.

If I call

```
Game.new.show
puts "This line is never called"
```

the game object enters into a loop and I can't manipulate it.

How can I create a window, show on screen and continue to manipulate it outside of subclassing behavior?

**Comment by jlnr** [comment]
Why does subclassing not work for you? What is the use case here?

Recent Gosu versions have an experimental `tick` method, like so:
```ruby
w = Gosu::Window.new(100, 100)
while w.tick
  puts "running"
end
puts "closed"
```

It is experimental because so far, no one has made good use of it (I think) - it is meant to allow Gosu to be integrated with GUI toolkits, but that hasn't really worked so far.

**Comment by quantumpotato** [comment]
Tick might work.
My use case is - I'm creating an IRC bot* that listens to chat commands in a server. I also run a Gosu game. The chat commands are sent to the game.

I've ended up doing

```
game = Game.new

bot = Bot.new(game)

Thread.new {
  bot.start
}

game.show
```

* bot built with https://github.com/cinchrb/cinch

**Comment by jlnr** [comment]
Ha, an IRC bot using Gosu? That's intriguing :)

Yeah, that'll do the trick. I should also note that Gosu is not thread-safe at all, and `Gosu::Window` can only be used on the main thread (a limitation of OS libraries). So even `Image#from_text` etc. cannot be called on a background thread (not yet, anyway). The bot can only communicate with the window via thread-safe data structures.
