### ISSUE TITLE
Make Gosu::Color a proper Hash key

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#316]
Needs `#hash` (which can be `#rgba`/`#gl`) and `#eql`? (which can be `#==`) 

Reported by @shawn42

**Comment by Kjarrigan** [comment]
Hi there,

I use Gosu for quite a while now and I would like to take a deeper look and maybe help with some issues. The problem I currently have is, that you got quite some files/code in this repo. Do you have some guideline for me? Maybe a short description of the basic gosu concept (I raed something about SDL2 as Base but not some kind of Render-System?) and which files to start looking at.

Specific to that Issue - can you clarify that a bit. I didn't find a related topic in the forums where this was discussed / reported. As I understand it should do something like this?

```ruby
c1 = Gosu::Color.new(FOO)
c1.hash 
#=> rgba or gl representation of the color

c2 = Gosu::Color.argb(BAR)
c2.eql?(c1)
# => false
```

Wenn es hilft, nehme ich den Crashkurs Gosu-Entwickler auch gern in Deutsch :smile:, wobei ein englischer Guide vielleicht auch dem ein oder Anderen die Möglichkeit eröffnet zu Gosu beizutragen, der bisher (wie ich) etwas von der Komplexität abgeschreckt wird.

**Comment by jlnr** [comment]
@shawn42 Merged, thanks!

@Kjarrigan I'm not sure if you are still subscribed to this issue, but keep your eyes open for a "Hacking Gosu" guide in the future. It is indeed hard to dive into Gosu's source code right now :(
