### ISSUE TITLE
Implement render-to-image / screenshot functionality

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#317]
Maybe screenshots can be implemented with a few SDL 2 calls: http://stackoverflow.com/a/22339011

Inspired by this thread: https://www.libgosu.org/cgi-bin/mwf/topic_show.pl?tid=1265

**Comment by jlnr** [comment]
Since Gosu does not use the SDL_Renderer_* family, it will take a bit more code than that :(

**Comment by djzk** [comment]
Another feature I'd like to see :)

**Comment by jlnr** [comment]
I think screenshots are a special case, and if we had `render { ... }` in addition to `record { ... }`, we could implement screenshots *and more* with that.

**Comment by jlnr** [comment]
I can't really find a solution that's less convoluted than this... https://github.com/datenwolf/codesamples/blob/master/samples/OpenGL/minimalfbo/minimalfbo.c

**Comment by Juksefantomet** [comment]
Might this be something of use? i might be off, and i see that it's mainly for windows platform, but if it's on the road in the right direction anything helps right? 👍 

https://github.com/jarmo/win32screenshot

**Comment by jlnr** [comment]
Also check out this approach which uses the Ruby OpenGL libraries: https://www.reddit.com/r/gosu/comments/6wjjsr/saving_rendered_image/

Has been posted just three days ago :)
