### ISSUE TITLE
Version 0.10.6 won't install from RubyGems

### ISSUE THREAD

**Issue by GeekFitness** [gosu/gosu#319]
[I posted about it on StackOverflow, too](http://stackoverflow.com/questions/35854744/rubygem-gosu-0-10-6-install-error-on-windows-10-using-gem-install-gosu), because I don't know how to install that version another way. Version 0.10.6 on RubyGems is invalid/corrupt. I could install 0.10.5, but not the newest one.

**Comment by jlnr** [comment]
That's strange, I've tested the gem with Ruby 2.2.2p95 x64 & latest RubyGems on Windows 7 and everything seems to work fine.
Does it work if you directly download the .gem file and then install it by passing the filename to `gem install`? Maybe a broken version of the file got stuck in your local RubyGems cache?
https://rubygems.org/downloads/gosu-0.10.6-x64-mingw32.gem

If not, I guess I'll have to update my Ruby 2.2 installation to your version and retry :)

**Comment by GeekFitness** [comment]
The local version worked. I have no idea why the patching and downloading wouldn't. I'm not behind a restrictive firewall or anything of the sort. I also had no idea how to download and install until this. So thank you! :)
