### ISSUE TITLE
Improper image header error using `to_blob`

### ISSUE THREAD

**Issue by RobinClowers** [gosu/gosu#327]
I'm trying to transpose a tile from a png loaded with the `load_tiles` method. When I try to load the blob into RMagick:

```
tiles = Image.load_tiles("spritesheet.png", 48, 48)
Magick::Image.from_blob(tiles[0].to_blob) {
  self.format = "PNG"
}.transpose!
```
It fails with this error:

```
`from_blob': improper image header `' @ error/png.c/ReadPNGImage/3921 (Magick::ImageMagickError)
```

I have libpng installed, do I need to set some other properties for RMagick?

**Comment by jlnr** [comment]
Off the top of my head, `self.format = 'RGBA'` should fix the issue. Can you please give it a try? If it works, I'll make a note in the rdoc.

**Comment by RobinClowers** [comment]
Thanks for getting back to me quickly! That makes sense, but it doesn't seem to work either. After updating format, it complained about needing size set. Once I set the size, I got this error:

```
`from_blob': unexpected end-of-file `': No such file or directory @ error/rgb.c/ReadRGBImage/239 (Magick::ImageMagickError)
```

Here is my code now:

```
Image.new(
  Magick::Image.from_blob(image.to_blob) {
    self.format = "RGBA"
    self.size = "#{image.width}x#{image.height}"
  }.transpose!
)
```

**Comment by jlnr** [comment]
See https://www.libgosu.org/rdoc/Gosu/Image.html#to_blob-instance_method

`.depth = 8` was missing :)

**Comment by RobinClowers** [comment]
Sure enough, that did the trick! Thanks for your help.
