### ISSUE TITLE
Apps all full screen on Raspberry Pi

### ISSUE THREAD

**Issue by adkron** [gosu/gosu#328]
When running any gosu program on the Raspberry Pi it takes over the whole screen and doesn't open in a window. I can't figure out how to close it either. The same programs work on the OSX install. My son is trying to go through the pragmatic studios book on game programming and when we transferred everything to his PI we end up with this issue. I'm not sure how to debug it because it seems to take over and I don't know how to get back to the terminal.

**Comment by jlnr** [comment]
Gosu on the Pi only supports fullscreen mode, it has to do with the way the OpenGL context is created. Have you added something along these lines to the window:

```ruby
def button_down(id)
  close if id == Gosu::KbEscape
end
```

That should actually work... If not, what happens instead? Does the game even appear on screen?

**Comment by jlnr** [comment]
Closing because I can't tell if there's really a bug involved.
