### ISSUE TITLE
Gosu::Shape

### ISSUE THREAD

**Issue by RomanADavis** [gosu/gosu#330]
The new Image syntax is awesome, allowing objects to draw without constantly passing around window. The same, however, does not apply to Gosu::Window#draw_quad(),

I'm proposing that shapes get their own class, Gosu::Shape, with it's own Gosu::Shape#draw() method. I think this will make drawing and animating shapes a lot simpler and less clunky.

**Comment by jlnr** [comment]
Glad to hear you like the new syntax :)

`draw_quad` has moved to the Gosu module (below the long list of constants...), so you can call it as `Gosu.draw_quad` throughout your app:

https://www.libgosu.org/rdoc/Gosu.html

Third-party gems can build more convenient classes on top of these primitives (feel welcome :)), but that's not something that I can maintain inside "core" Gosu - the current scope is just about manageable by a single person.
