### ISSUE TITLE
Failed to install native extensions on PocketCHIP (Arm Linux, Debian 8)

### ISSUE THREAD

**Issue by andrewhavens** [gosu/gosu#331]
After waiting a few years after supporting the initial Kickstarer, I just received my [PocketCHIP](https://getchip.com/pages/pocketchip) in the mail. I'm working on getting some Ruby-based 2D programming up and running. As far as I know, I have installed all of the dependencies necessary to run Gosu. However, when I try to install it, it fails:

``` sh
chip@chip:~$ cat /var/lib/gems/2.1.0/extensions/arm-linux/2.1.0/gosu-0.10.7/gem_make.out
/usr/bin/ruby2.1 extconf.rb
The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/gosu/gosu/wiki/Getting-Started-on-Linux

checking for TTF_RenderUTF8_Blended() in -lSDL2_ttf... yes
checking for SDL_ttf.h... yes
checking for main() in -lopenal... yes
checking for AL/al.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling stb_vorbis.c
compiling gosu_wrap.cxx
gosu_wrap.cxx: In function 'VALUE _wrap_Font_draw_rot(int, VALUE*, VALUE)':
gosu_wrap.cxx:5474:111: warning: 'void Gosu::Font::drawRot(const wstring&, double, double, Gosu::ZPos, double, double, double, Gosu::Color, Gosu::AlphaMode) const' is deprecated (declared at ../../Gosu/Font.hpp:81) [-Wdeprecated-declarations]
       ((Gosu::Font const *)arg1)->drawRot((std::wstring const &)*arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
                                                                                                               ^
compiling Window.cpp
In file included from ../../src/Window.cpp:2:0,
                 from Window.cpp:1:
../../src/Graphics/Common.hpp:20:21: fatal error: GLES/gl.h: No such file or directory
 #include <GLES/gl.h>
                     ^
compilation terminated.
Makefile:216: recipe for target 'Window.o' failed
make: *** [Window.o] Error 1

make failed, exit code 2
```

Am I missing a dependency? Or is Gosu not finding the right dependencies?

**Comment by jlnr** [comment]
Hm, I remember reading the notification mail, I even went to the CHIP website and died in their example game, but then I somehow overlooked this issue for a month. Oops...

Getting OpenGL ES to work on the original Raspberry Pi was a bit tricky, but in the end it boils down to this special-case code in `extconf.rb`, which links extra libraries: https://github.com/gosu/gosu/blob/master/ext/gosu/extconf.rb#L113-L120

...and the assumption that every `__arm__` platform has a header called `GLES/gl.h`:
https://github.com/gosu/gosu/blob/master/Gosu/Platform.hpp#L65-L68

It seems that this does not apply to the PocketCHIP. Have you found any trace of OpenGL headers/libraries so far?

**Comment by jlnr** [comment]
Closing this as there was no progress in a while.
