### ISSUE TITLE
Modification suggestion in the wiki page for installing guso

### ISSUE THREAD

**Issue by db0sch** [gosu/gosu#334]
Hi, 
In your wiki page, you advise to install gosu with this command : `sudo gem install gosu`

But i'm really not sure about adding `sudo` before a `gem install`.

I'm pretty sure `gem install gosu` should be enough.
Actually, we encounter some problems with this command, while the simple `gem install gosu` worked perfectly.

Shall we change the wiki?

----

According to this Stackoverflow topic, it depends whether you use a Ruby Version software (like RVM or RBENV... I use rbenv) : http://stackoverflow.com/questions/2119064/sudo-gem-install-or-gem-install-and-gem-locations
If so, maybe the wiki should be more specific about it, providing both solution for user with or without a ruby version manager.
What do you think ?

Thank you

**Comment by jlnr** [comment]
Thanks. I think that's a good idea, because `sudo` users are probably in the minority nowadays. Both Wiki pages already include this information, though.

Getting Started on OS X:
> Install the gem via sudo gem install gosu. Omit the sudo if you use rbenv or rvm to manage your Ruby installations.

Getting Started on Linux:
> # If you are using rvm or rbenv, do not use 'sudo'

Which page did you follow? Do you think it would be easier to notice if it was closer to the command? Feel free to edit the wiki, I'm not good at documentation :)

**Comment by db0sch** [comment]
I followed these pages : https://github.com/gosu/gosu/wiki/Getting-Started-on-Linux
and this one : https://github.com/gosu/gosu/wiki/Getting-Started-on-OS-X
(I work on Ubuntu, and I help people working on MacOSX, as a teacher assistant).

You're right about the information regarding RVM and RBENV. I read the documentation too fast.
And I'm sure the students didn't even bother to read the line. Sorry about that.

Maybe the comment color code doesn't help to catch this information?

Maybe something like this : 
```
# If you are using rvm or rbenv:
gem install gosu
# otherwise :
sudo gem install gosu
```
It'll force the reader to ask himself which one to use.
What do you think?

Thanks for your reply anyway.
Best

**Comment by jlnr** [comment]
Oh, does that mean Gosu is being used as a teaching tool once more? :)

I really like your suggestion. Feel free to edit the wiki if you have a minute (both pages), otherwise I'll do it when I get back home on the weekend.

**Comment by db0sch** [comment]
Yes it is [😊] . By Le Wagon (https://www.lewagon.com/fr). +> Great code bootcamp, btw.


I'll change the wiki right away.


Best

Dimitri

________________________________

**Comment by jlnr** [comment]
Interesting! Thanks for the Wiki fix too ✌️
