### ISSUE TITLE
FPS very low for large window sizes

### ISSUE THREAD

**Issue by MJoergen** [gosu/gosu#338]
The short ruby program below shows an FPS of around 17. Since there is no logic involved, just an empty screen, this is very surprising. Testing has shown that smaller window sizes leads to increased FPS.

This is observed on a dual-core machine running Fedora 24 with the following versions:
```
ruby-2.3.1-56.fc24.x86_64
SDL2-2.0.4-6.fc24.x86_64
xorg-x11-server-Xorg-1.18.4-1.fc24.x86_64

gosu (0.10.7)
```
While running, the root process Xorg is using about 90 % of CPU time (according to 'top').

The command 'xrandr' gives the following output:
```
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 640 x 480, current 1920 x 1200, maximum 1920 x 1200
default connected 1920x1200+0+0 0mm x 0mm
   1920x1200      0.00* 
   1600x1200      0.00  
   1280x1024      0.00  
   1280x800       0.00  
   1024x768       0.00  
   800x600        0.00  
   640x480        0.00  
```

Where are all the CPU cycles spent?

```
require 'gosu'

class GameWindow < Gosu::Window
  def initialize
    super(1600, 1000, false)
  end

  def update
    self.caption = "Gosu  -  [FPS: #{Gosu::fps.to_s}]"
  end

  def draw
  end
end

window = GameWindow.new
window.show
```

**Comment by jlnr** [comment]
Does OpenGL hardware acceleration work on your machine? If not, that would explain both the terrible framerate as well as the busy CPU - all these pixels are filled in software.

**Comment by MJoergen** [comment]
You were right: The OpenGL hardware acceleration was not working. I fixed it, and now the FPS is working as expected. Thanks!
