### ISSUE TITLE
Evaluate Rice as a SWIG replacement

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#356]
I needed to add another silly PATCH hack to my SWIG-generated wrapper code in #352 to fix UTF-8, and Ruby support in SWIG does not seem like a priority ([see this file and its history]( https://github.com/swig/swig/blob/master/Lib/ruby/rubywstrings.swg)).

Maybe Rice would be a better option? https://github.com/jasonroelofs/rice

I'm mostly worried that I'd have to manually export dozens of button constants with Rice, which is something that works beautifully with SWIG. I also don't want to write more code generators.

In theory, SWIG has the advantage of working with languages other than Ruby, but I think it's time to give up on that dream...

**Comment by Kjarrigan** [comment]
Yesterday I talked with my coworker about SWIG and he has some "problems" with SWIG in one of his gems as well. He maintains some C(++) gems and today would always prefer to write a native rubybinding himself. Would that be an option to write the binding code itself? It shouldn't be that hard and you don't add new stuff every day so the maintenance should be minimal and time-wise comparable to making the latest swig stuff work again.

**Comment by jlnr** [comment]
My biggest worry is that I will start to re-invent SWIG/Rice with C macros, Ruby scripts that generate lists of constants etc., because it is so tempting to automate boilerplate code generation. :/

Sent from my iPad

**Comment by jlnr** [comment]
One consideration here should be support for mruby, which might be the key to reliably shipping compiled (closed-source) games on Windows.

**Comment by jlnr** [comment]
Closing this since @cyberarm is already working on FFI support, which seems to be the more common alternative to SWIG.
