### ISSUE TITLE
Alt+Enter / cmd+[ctrl+]F should toggle fullscreen by default

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#361]
macOS: cmd+F is the default shortcut to toggle fullscreen in video players, cmd+ctrl+F is a common shortcut to enable fullscreen in other desktop apps (Safari, Mail, Finder, …).

Windows (and maybe Linux?): Alt+Enter is the default shortcut to toggle fullscreen in games.

Gosu games should support this by default because not every user is aware of each platform's conventions. I'm not sure if Gosu should always enforce these shortcuts, or if it should be the default implementation of `Window#button_down` which people can decide to invoke via `super` or not.

**Comment by Kjarrigan** [comment]
Hah, yesterday I thought maybe it would be a good idea to have a default binding for the gosu licenses (like F1). So I like your proposal of some default key bindings, but prefer the ```super``` version.

**Comment by jlnr** [comment]
Good points. I agree that it needs to be documented. I have added rdoc for the new default implementation, and I will update the tutorial wiki page to explain the default shortcuts too.

**Comment by jlnr** [comment]
Hmmm, I'm not sure where to show the LICENSES by default. The idea is that you should include them in your credits screen (assuming there is one...), which is what I do in my iOS game. I'm not sure whether hiding the attributions behind a F1 default shortcut is sufficient if you don't also document that shortcut in your game. And then you might as well just print the licenses in your game.

**Comment by Kjarrigan** [comment]
But we should definitely to make it clearer that you should include them somewhere, because as I said. Until I worked on that PR I didn't know about that. Maybe instead of an default binding extends the rdoc and add it to the Captain Ruby Example? Who ever starts with gosu will likely use that as first reference. But it might be worth a seperate issue then.

**Comment by jlnr** [comment]
@Kjarrigan Maybe it should just have its own sidebar entry in the `gosu-examples` gem to show the LICENSES string and explain its use at the same time. I'll have to update the `gosu-examples` gem anyway, it uses lots of deprecated stuff.

**Comment by Hi2885** [comment]
Add code
