### ISSUE TITLE
Gosu should create directories if necessary

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#365]
For example, `image.save("screenshots/5.png")` should automatically create the `screenshots` folder if it doesn't exist. This is *always* what we want, and frees users from having to call `mkdir_p` just in case.

**Comment by mblumtritt** [comment]
My 2 cents about this:
A gem should solve a dedicated class of problems. Gosu solves graphic & sound & input - you see that are already three problem classes. I would prefer to solve file handling problems with file handling focused gems.
And: you are free to extend `Gosu::Image` in your project :)

**Comment by RavensKrag** [comment]
I agree with mblumtritt, and would like to add another point.

The proposal says

> This is _always_ what we want

but that is not completely true. This is only true for code that is completely bug free.

If I want my screenshots directory to be `screenshots` but I make a typo and forget the 's' and write `screenshot` instead, the proposed system will create an extra, unwanted directory. When I go to look in my `screenshots` directory later,  I will be confused when the files are not there. (This is not hypothetical. I've made this sort of bug more than once.)

If you use `mkdir_p` in one section of the code, and later use the created directory, you can catch this problem.

```ruby
FileUtils.mkdir_p("screenshots") # plural, with an 's'
# creates directory, no errors.
image.save("screenshot/5.png") # no 's'
# can't find the directory. gives error.
```

Ruby won't be able to tell you "hey, you missed that 's'" but at least it will let you know there's a problem.

**Comment by jlnr** [comment]
I agree with you about file management being outside of Gosu's scope, and I really want to remove all this junk from Gosu's public (C++) interface: https://github.com/gosu/gosu/blob/master/Gosu/IO.hpp

I'm closing this ticket because no other library in Ruby has this behavior (writing via `File.new` will fail if the directory does not exist), so this feature could actually introduce confusion in the long term. In C++, [`create_directories`](http://en.cppreference.com/w/cpp/experimental/fs/create_directory) is finally coming in C++17, so that's no reason to include it in Gosu either.

I'll still keep the filesystem-related #363 open because it's such a common and unnecessary stumbling block.

Thanks for the feedback & for keeping Gosu minimal!
