### ISSUE TITLE
Ruby/Gosu needs deprecations

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#367]
Ideally, Gosu's C++ core should only support the canonical way to do everything, and `patches.rb` should be renamed to `compat.rb` and provide all the backwards compatibility code. The first time a deprecated feature is used, a warning should be printed.

The goal is not to get rid of the compat code (it's trivial to keep it in Ruby), but to ensure that existing Gosu projects converge towards a coherent, modern style of using Gosu.

**Comment by Kjarrigan** [comment]
> The goal is not to get rid of the compat code (it's trivial to keep it in Ruby)
I think deprecated code should at some point be removed. If your code depends on this you can always choose to use the "old" gosu version. Gosu 1.0 would be a good release to throw away all the compatibility stuff.

**Comment by jlnr** [comment]
I think it's quite normal to write games with Ruby/Gosu, abandon them for years, and then come back to them. I also think that being able to run and inspect 10+ years of games is one of Gosu's strengths. People should be nudged into modernising their games through deprecation warnings, but I wouldn't want to actually break games without good reason. Fixing outdated Ruby code is just *so* painful :(

Superseded by #370.
