### ISSUE TITLE
Window#needs_redraw? is broken in Ruby

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#376]
Throws this error:

```
/lib/gosu/patches.rb:152:in `tick': SWIG director type mismatch in output value of type 'bool' (RuntimeError)
```

See https://www.libgosu.org/cgi-bin/mwf/topic_show.pl?pid=9080

I'm not even sure for how long it has been broken. The method is badly named anyway (should be `need_redraw?` in Ruby) and its use cases are limited, maybe I'll just remove it. It won't break any code, maybe just make it less efficient.

**Comment by Kjarrigan** [comment]
Hm. I used that a few times in menues as they usually are static and only need to be redrawn when another button ist selected or something like that. I think I last used it with some gosu-0.9.x? And its part of this Book: [Developing Games With Ruby](https://leanpub.com/developing-games-with-ruby/read). I really like this and every now and then used it as reference... So if your can repair it without too much effort and stuggling with swig, I guess it would be worth it? Dunno.

**Comment by jlnr** [comment]
Ah, I hadn't yet checked if it's in the book. Yeah, everything that's in the book should stay. And I think it is interesting for educational purposes.

My thinking was that in *real* games, the screen will never be static. Every commercial 2D game will have scrolling backgrounds, characters will have idle animations, etc.

**Comment by jlnr** [comment]
Ouch. To quote myself from the forum thread above:

`needs_redraw?` is not actually broken, the error message is just extremely misleading.

What is happening is that if an exception is raised in `needs_redraw?`, then this exception will be swallowed by a safety mechanism inside Gosu, and SWIG will print the wrong error message.
