### ISSUE TITLE
Encoding::CompatibilityError 

### ISSUE THREAD

**Issue by Kjarrigan** [gosu/gosu#385]
Reported at /r/gosu by KoBeWi:

> lib/gosu.rb:9 | Incompatible character encodings: UTF-8 and Windows-1250 
> It happens when you run Ocra executable, with username containing Unicode characters.

**Comment by jlnr** [comment]
Oh wow. Line 9 is:

```ruby
  ENV['PATH'] = "#{binary_path};#{ENV['PATH']}"
```

Looks harmless, doesn't it? It seems other Ruby tools (Vagrant, Puppet) have experienced similar issues on Windows. Off to create a new Windows user...

**Comment by jlnr** [comment]
I've created a user named "Böhßer Tühp" and stared into the abyss. `ENV['PATH']` must be in a Windows encoding, `$LOAD_PATH` needs to be exclusively UTF-8, and Ruby itself uses "C:\Users\BHSTHP~1\..." a lot. It seems to work with a simple fix, though.
