### ISSUE TITLE
Gosu::Color#hue returns wrong values in specific scenarios

### ISSUE THREAD

**Issue by Kjarrigan** [gosu/gosu#391]
Another strange behaviour I found while writing the Color-TestSuite. 
When creating a color as (A)RGB I get a NaN for hue (see line 006)
When creating a color as (A)HSV) I get a float (see line 014) but it should be 1 (according to the docs it should be an integer) or at least 1.0

```ruby
$ irb -rgosu

:001 > c = Gosu::Color.new(255,255,255,255)
=> #<Gosu::Color:ARGB=0xff_ffffff> 

:002 > c.red
=> 255 

:003 > c.green
=> 255 

:004 > c.blue
=> 255 

:005 > c.alpha
=> 255 

:006 > c.hue
=> NaN

:007 > c.saturation
=> 0.0 

:008 > c.value
=> 1.0 

:010 > x = Gosu::Color.from_ahsv(100, 1, 1.0, 1.0)
=> #<Gosu::Color:ARGB=0x64_ff0400> 

:011 > x.red
=> 255 

:012 > x.green
=> 4 

:013 > x.blue
=> 0 

:014 > x.hue
=> 0.9411764705882353 

:015 > x.saturation
=> 1.0 

:016 > x.value
=> 1.0 

```

**Comment by jlnr** [comment]
Gosu::Color only uses 8 bits per RGB channel, the conversion from HSV to RGB and back will always be lossy.

Saturated colours are relatively accurate:

```ruby
def roundtrip(h)
  Gosu::Color.from_hsv(h, 1.0, 1.0).hue
end

360.times { |hue| puts hue - roundtrip(hue) }
```

For `s = 0.1` the error is larger, and `roundtrip(roundtrip(h))` increases the error as well. Maybe the latter is a bug.

**Comment by Kjarrigan** [comment]
Ok. So line 14 "works as intended" but is line 6 - NaN correct?

**Comment by Kjarrigan** [comment]
If this "intended" maybe we should at least change the rdoc from Integer to Float as Return-type as at least I didn't expect that at all (maybe because I never really looked into the math behind the rgb <> hsv conversion). And I have no problem with the "blur". I don't want to create color proof print products and as men I didn't care that much about color nuances :smile:

#hue ⇒ Integer
The color's hue in the range (0…360).

**Comment by jlnr** [comment]
I really don't know I documented `hue` as `Integer`, thanks for pointing that out.
