### ISSUE TITLE
Gosu does not support MP3 files

### ISSUE THREAD

**Issue by leddy231** [gosu/gosu#393]
```ruby
require "gosu"

class Window < Gosu::Window
	def initialize
		super(1000, 1000, false)
		Gosu::Song.new("test.mp3").play
	end
end

Window.new.show
```
Where test.mp3 is a fresh mp3 file from audacity, or a downloaded song.
Produces the following error
```
AL lib: (EE) LoadHrtf: Could not open default-44100.mhr
AL lib: (EE) GetHrtf: Incompatible format: 5.1 Side 44100hz
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gosu-0.11.3.1-x64-mingw32/lib/gosu/compat.rb:128:in `initialize': File contains data in an unknown format. (RuntimeError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gosu-0.11.3.1-x64-mingw32/lib/gosu/compat.rb:128:in "initialize"
        from audiotest.rb:6:in "new"
        from audiotest.rb:6:in "initialize"
        from audiotest.rb:10:in "new"
        from audiotest.rb:10:in "<main>"
```
Tried both 64 and 32 bit ruby, both latest gosu and gosu 0.10.7 which i had installed
Audio files and code works on Mac

**Comment by jlnr** [comment]
On Windows and Linux, Gosu uses libsndfile to load audio (except OGG files) which [does not support MP3 files](http://www.mega-nerd.com/libsndfile/FAQ.html#Q020).

As far as I understand the situation, the patents for MP3 have already started expiring, and [the Fedora project was able to add MP3 decoding support last year](https://fedoraproject.org/wiki/Multimedia/MP3). So it should be reasonably safe for Gosu to add MP3 support now, and I'll rename this issue accordingly.

**Comment by jlnr** [comment]
In the meantime, the easiest workaround is to convert your file to the Ogg Vorbis format.

**Comment by leddy231** [comment]
Oh there never was mp3 support? Huh... Well hopefully it can get it soon. Was hoping my user(s) could add mp3s directly to a folder, but i have to convert them first then.

**Comment by jlnr** [comment]
"Depends" :) MP3 files are supported on macOS and iOS, where Gosu uses OS APIs to decode music, and they used to be supported on Windows and Linux, but then you would technically have to pay $2500 in license fees to release a game.

**Comment by jlnr** [comment]
I've found two candidate libraries for MP3 decoding.

MiniMP3 is a simple decoder based on ffmpeg: http://keyj.emphy.de/minimp3/

Annoyingly, it is licensed under the LGPL. On Windows, I could fork libsndfile and include minimp3 in libsndfile.dll, but what about Linux, where Gosu uses the vanilla libsndfile package? Hmm. I really don't want to bake LGPL code into the Gosu binary.

And then there is the Fluendo MP3 decoder: https://core.fluendo.com/gstreamer/svn/trunk/gst-fluendo-mp3/

It is released under the MIT license and seems to be well-maintained, but it is written for the GStreamer infrastructure, so it will need a lot of refactoring to fit into Gosu.

**Comment by leddy231** [comment]
SFML has mp3 support, anything you could grab from there?(zlib license, you can do alter it as much you want) Annoyingly, Windows support would be enough for most users, but personally i need it in linux (raspberry pi)

**Comment by jlnr** [comment]
Does SFML really support MP3 files? This tutorial says it doesn't:

https://www.sfml-dev.org/tutorials/2.4/audio-sounds.php

I couldn't find a matching decoder in its source either.

**Comment by jlnr** [comment]
And another candidate - libmpg123 could be added as another DLL on Windows, and is available as an unofficial package for many Linux distros: https://www.mpg123.de/features.shtml

**Comment by leddy231** [comment]
Ah sorry only the old version of SFML did.
http://www.zinf.org/faq.php could this be of any use? Its a full player but it includes a mp3 decoder source (which looking at the FaQ its popular to poke in it) Could not find any license apart from "free"

**Comment by jlnr** [comment]
zinf is under the GPL, according to the COPYING file in its source tarball.

**Comment by jlnr** [comment]
Removing "help wanted" tag as I've started working on this

**Comment by jlnr** [comment]
Closing this, #397 works on macOS and only needs to be prepared for release on Windows/Linux now.
