### ISSUE TITLE
Latest stable release? 0.11.3 or 0.11.3.1?

### ISSUE THREAD

**Issue by ilovezfs** [gosu/gosu#396]
https://github.com/gosu/gosu/releases
https://github.com/gosu/gosu/releases/latest

still shows 0.11.3 but there is a tag for 0.11.3.1. Which is actually the latest stable version? I'm asking because we have PR opened to homebrew/core for 0.11.3.1.

See https://github.com/Homebrew/homebrew-core/pull/11979.

**Comment by jlnr** [comment]
Gosu 0.11.3.1 is a Ruby-only release and does not require a formula upgrade in Homebrew, I've updated the releases list accordingly.

**Comment by ilovezfs** [comment]
Thanks for the clarification.
