### ISSUE TITLE
Issues on rmagick integration (Windows)

### ISSUE THREAD

**Issue by taroxd** [gosu/gosu#403]
OS: Windows 10 Build 16188
RMagick: 2.16.0
ImageMagick: 6.9.8-4 x64
gosu: 0.12.0

Test Code:
```ruby
require 'gosu'
require 'rmagick'

include Magick

magick_image = Magick::Image.new(640, 480)

magick_image.color_reset!(Pixel.new(10, 20, 30, 255))

# output 20
p magick_image.pixel_color(0, 0).green

gosu_image = Gosu::Image.new(magick_image)

# output 0
p Magick::Image.from_blob(gosu_image.to_blob) {
  self.format = "RGBA"
  self.size = "#{gosu_image.width}x#{gosu_image.height}"
  self.depth = 8
}.first.pixel_color(0, 0).green
```

And following code produces a black window:
```ruby
require 'gosu'
require 'rmagick'

include Magick

class BugWindow < Gosu::Window
  def initialize
    super(640, 480)
    self.caption = "Bug"
    magick_image = Magick::Image.new(640, 480)
    magick_image.color_reset!(Pixel.new(10, 20, 30, 255))
    @gosu_image = Gosu::Image.new(magick_image)
  end

  def update
  end

  def draw
    @gosu_image.draw(0, 0, 0)
  end
end

BugWindow.new.show
```

**Comment by Kjarrigan** [comment]
Not just a windows issue. Same results as above on Ubuntu 14.04 with
RMagick v2.16.0 and ImageMagick 6.7.7-10

**Comment by jlnr** [comment]
Not a bug. The RGBA values of an RMagick::Pixel are in the range [0; RMagick::QuantumRange], not [0; 255] or [0.0; 1.0]:

https://rmagick.github.io/struct.html#Pixel

So the green component is truncated to 20/255 = 0 when converting the RMagick::Image into a Gosu::Image, which always uses 8-bit colour channels. The quick fix is to use this color instead:

```ruby
magick_image.color_reset!(Pixel.new(10 * 255, 20 * 255, 30 * 255, 255 * 255))
```
