### ISSUE TITLE
Raspberry Pi 3 running Raspbian issue

### ISSUE THREAD

**Issue by ghost** [gosu/gosu#410]
When running a simple Gosu application on Raspian, the screen shows only black, however it still registers input, and it still updates/draws on the main window. 

Edit:

After having to interrupt the program to stop it, it shows these errors. Could that help at all?
from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gosu-0.12.1/lib/gosu/swig_patches.rb:47:in `show'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gosu-0.12.1/lib/gosu/swig_patches.rb:47:in `show'
	from gosuMovement.rb:81:in `<main>'

**Comment by jlnr** [comment]
I don't have a RPi 2/3 test device, so I don't think I can help. Hopefully someone else will notice this thread. If you are a reddit user, you could also open a thread there and see if you can ping any other users who have successfully used a Pi.

**Comment by cyberarm** [comment]
I've been using Gosu on my Raspberry Pi 3 (B rev2) without issue.
Might be able to close this issue and prune the back log.

**Comment by jlnr** [comment]
@cyberarm Thanks for the confirmation :) Agreed.
