### ISSUE TITLE
Overriding Window#close prevents throwing exceptions

### ISSUE THREAD

**Issue by KoBeWi** [gosu/gosu#411]
When you override Window#close with e.g. empty method and then an exception is thrown, instead of being printed as usual, whole application just freezes, because window can't be closed. So maybe if Window catches an exception, it should call close! instead of close, or whatever it is implemented. Or do some method call whenever something is thrown inside Window and not caught otherwise.

**Comment by jlnr** [comment]
Good catch (y) I've committed a fix.
