### ISSUE TITLE
Update "misses" input

### ISSUE THREAD

**Issue by leddy231** [gosu/gosu#416]
So i have been having some issues with using a barcode scanner together with gosu, and i think i found the problem.
The setup is as follows: The scanner class puts a text_input on the window to record the characters, and when the enter key is pressed (which the scanner does when it has read a barcode) the text gets emptied and sent for processing. However sometimes the enter key gets missed, and the text is never cleared or sent. This only happened when the scanner class checked if the enter key was pressed during update, but the enter key always works from the button_down call.
It seams that if the update runs too slow, it can miss keys being pressed. Thats why it worked flawlessly on my dev machines, but struggled on the old hardware its running on in the end.

To simulate this:

	  require "gosu"

	  class Window < Gosu::Window
	    def initialize
	      super(1000, 1000, false)
	    end

	    def update
	      1000000.times do
	        Math.sqrt(136335) #simulates slow machine, increase if you run a supercomputer
	      end
	      puts "--- Update down A" if Gosu::button_down?(Gosu::KbA)
	      puts "--- Update down B" if Gosu::button_down?(Gosu::KbB)
	    end

	    def button_down(id)
	      puts "button down A" if id == Gosu::KbA
	      puts "button down B" if id == Gosu::KbB
	    end
	  end

	  Window.new.show

Run the above code and lightly press the keys (or even better use software to simulate rapid input). The button_down will always work, the update might not.

This means all objects that need reliable keypresses needs to hook into the windows button_down call, instead of just checking the button during update, which is a lot smoother.
I guess a fix in gosu would be to store all keypresses between updates and make sure they are "visible" during the next update. Slow key presses are better than missed ones.

**Comment by jlnr** [comment]
Sorry for the trouble, I see why that would be awful to debug. Gosu is working as intended here though, `button_down` is the right tool for the job. It will ensure that each keypress arrives once (and only once) and that multiple keys also arrive in the right order.
