### ISSUE TITLE
Constants Button::KbBackslash and Button::KbSlash are identiacal

### ISSUE THREAD

**Issue by mblumtritt** [gosu/gosu#426]
Using MacOS (High Sierra) I found that
```ruby
refute_same(Gosu::Button::KbBackslash, Gosu::Button::KbSlash)
```
failed with Gosu v0.13.1.

Both have the value 49. Furthermore key code 56 is not defined by any constant in Gosu::Button.

**Comment by mblumtritt** [comment]
See also `https://github.com/gosu/gosu/blob/master/Gosu/Buttons.hpp#L64` and `https://github.com/gosu/gosu/blob/master/Gosu/Buttons.hpp#L69`

**Comment by jlnr** [comment]
Thanks! That'll make a good hotfix to go along with #424 as a point release. I'll look into it ASAP.

**Comment by mblumtritt** [comment]
Thanks a lot! 🚀
