### ISSUE TITLE
Drop Ruby < 2.0 (or even < 2.3) Support

### ISSUE THREAD

**Issue by Kjarrigan** [gosu/gosu#442]
Hi @jlnr,

thought about this topic again. You mentioned a few gems that are used with gosu which wouldn't work any longer. Can you tell me what gems you meant - maybe I can try to make them Ruby 2.x compatible. (I haven't really used anything besides gosu so far. I played a bit with chipmunk and have heard of Ashton and Texplay but never used any of those.)

Greeting,
Kjar

**Comment by jlnr** [comment]
Libraries that should be tested on Ruby 2.0 (I think that's a good baseline, some versions of macOS still use it):
- [ ] Texplay
- [ ] Ashton
- [ ] Releasy
- [ ] Maybe even fidgit? It's part of the Gosu org now.

I'm still hopeful that most broken stuff (shaders? Ashton's screenshot functionality?) can be salvaged into the Gosu gem proper. Having one binary gem in the community is enough of a burden IMHO... :(

Libraries that are out of scope:
- OpenGL (not in the Gosu org, has its own maintainers)
- Chipmunk (same)
- Chingu (some of it is already supported by Gosu itself)

**Comment by jlnr** [comment]
I was also thinking about this last night. I'm bundling utf8proc now for sane Unicode handling, and I think it'll add a few hundred KB to every `.so` file on Windows (the gem contains one binary for each Ruby version).

**Comment by shawn42** [comment]
Do feel free to check out chipmunk on the latest versions and let me know if it needs any love. I'm pretty much the only one maintaining it these days.

**Comment by Kjarrigan** [comment]
Thanks to you both. I'll See what I can do. I had a few minutes so I tried Texplay (as asthon has it as dependency) and it seemed to work with 2.4 (the first few examples worked). Just by the stars releasy is the most popular of your list. But I neither have a Windows nor Mac so we'll See how i could test it. 
But die I understand it corectly that merging e.g. asthon directly into gosu is an option?


To the increasing size problem I have no idea how to handle it atm. How do other gems handle this? I'll ask my coworker Lars. He has a lot mode experience in maintaining and deploying gems.

PS: writing on tablet with german autocomplete sucks...

**Comment by jlnr** [comment]
> merging e.g. asthon directly into gosu is an option?

Not a direct "copy and paste" merge :) But Ashton had screenshot functionality and we are already adding that. If Gosu has native texture shader support in the future, that could replace the Ashton gem (but probably with a different interface).

> To the increasing size problem I have no idea how to handle it atm.

I think dropping support for old Ruby versions every now and then will be a good start. 1.8 and 1.9 soon, 2.0 – 2.2 next year, ...

> How do other gems handle this?

I'm not sure if that's realistic at all, but in theory, Ruby Installer ships with a C compiler that could compile Gosu on demand. However, I'm not sure how the dependency on SDL 2 should be handled in this case. I don't want users to mess with `include` folders even if that is the intended way of installing binary gems.

I'm also worried that the Linux subsystem for Windows is going to kill Windows-based Ruby development in the long term... :/ (which would be great! Just not for Gosu)

**Comment by jlnr** [comment]
I've already kicked out the low-hanging fruit in -> #444

What's left in this issue is to drop support for Ruby 1.9 – 2.2 for Linux and macOS too, but that probably requires changes to the Travis CI setup. Not worth the effort until we really want to use Ruby 2.3+ languages features IMHO

**Comment by Kjarrigan** [comment]
Nice. A gold start :smile: I don't feel that well these days but hope to be in track soon to continue the outstanding issues.

**Comment by Kjarrigan** [comment]
One thing came to my mind though. If you really want to give mruby another shot then we have be to stick to 1.9

**Comment by jlnr** [comment]
np, take your time! And thanks for the warning about mruby. I am still blissfully unaware of how mruby changed after it was first released :)

**Comment by jlnr** [comment]
I've started using Ruby via RVM Ruby on Linux, instead of relying on Ruby 1.9 from apt: https://github.com/gosu/gosu/blob/master/.travis.yml

That means it's safe to drop 1.9 now. I could probably even kill 2.0-2.2 and start fresh with 2.3+.

**Comment by Kjarrigan** [comment]
:+1: :heart: :tada: 

I vote for start fresh with 2.3+

**Comment by jlnr** [comment]
I think it makes sense to tackle this at the same time we're adding support for keyword arguments -> moving this to Gosu 0.15. Hopefully I can release 0.14 after a few last-minute bug fixes for macOS.

**Comment by jlnr** [comment]
I have dropped support for Ruby < 2.5 in one of the latest PRs, which is the version that ships with Ubuntu 18.04, and I usually support the last two Ubuntu LTS versions.
