### ISSUE TITLE
macOS: Scaling breaks when moving window from Retina to normal screen or vice versa

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#452]
As reported by @shawn42:

> when moving a gosu window from my MBP screen to external (lower DPI) screen, all the sizing goes to crap

Sounds plausible. I should be listening for some kind of notification(?) and call `glViewport` again and all that to make up for the change in resolution. Or maybe Gosu should be using `max(DPI of all screen)` so that it doesn't matter?

**Comment by shawn42** [comment]
per: http://forums.libsdl.org/viewtopic.php?t=11311

> SDL 2.0.4 sends a window resize event when that occurs

**Comment by shawn42** [comment]
Probably need to recreate the window or something when that happens?

**Comment by jlnr** [comment]
I don't think this was related to HiDPI, but to multi-monitor support in general. Fixed by #459
