### ISSUE TITLE
" Developing Games With Ruby" Where can i find the working game code for the book

### ISSUE THREAD

**Issue by Kmak1234** [gosu/gosu#453]
Im trying to follow the tutorial but im stuck at creating prototype tank game.
Is there any updated code that works when compiling?

**Comment by shawn42** [comment]
@Kmak1234 Do you have a specific error that you're getting? Also, feel free to ask any questions on the Gosu Discord server: https://discord.gg/gTaHxdm

**Comment by Kmak1234** [comment]
Hello , thank you for your response it seems like that the code in the
books is outdated i have this kind of error.

**Comment by shawn42** [comment]
Thanks for the screenshot. The code is failing to load the `perlin_noise` rubygem. You can install it by either doing a `gem install perlin_noise` or using bundler in the root directory by doing: `gem install bundler && bundle install`.

**Comment by jlnr** [comment]
This should fix the issue! Closing this ticket. And I agree that Discord is probably the best place to ask, thanks for the link.
