### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by Alihusejn** [gosu/gosu#454]

**Comment by jlnr** [comment]
Nope, not right now. Ruby/iOS support through RubyMotion is pretty experimental and nobody has yet used it on the App Store, so I'm not going to invest in an Android port right now. But I'll leave this issue open for discussion and +1-ing etc. :)

**Comment by stain88** [comment]
There's already #273 about this, close as duplicate?

**Comment by jlnr** [comment]
Good catch! Thanks, closing this.
