### ISSUE TITLE
mouse_x/mouse_y values incorrect in fullscreen on macOS

### ISSUE THREAD

**Issue by netmute** [gosu/gosu#455]
I have a 1440x900 window. In window mode the bottom right mouse position is 1440x900, as expected. In fullscreen mode the bottom right mouse position is 810x506.
I have no idea what's going on 🤪

**Comment by jlnr** [comment]
Whoops, not sure how I could miss this for so long. Will look into it as part of v0.14

**Comment by jlnr** [comment]
SDL_GetGlobalMouseState() seems to be broken on macOS. First step: Send a bug report.

**Comment by jlnr** [comment]
I don't think this was related to HiDPI, but to multi-monitor support in general. Fixed by #459

**Comment by jlnr** [comment]
It seems that this will be fixed by #459. I can't reproduce this on macOS anymore.
