### ISSUE TITLE
macOS (Mojave beta): No rendering until window gets moved

### ISSUE THREAD

**Issue by Dan2552** [gosu/gosu#458]
I'm coming across an issue where the window doesn't render anything (shows black) until the window is moved. It's reproducible 100% of the time for me.

Before window is moved:
<img width="752" alt="screenshot 2018-09-01 at 16 38 44" src="https://user-images.githubusercontent.com/1478221/44947498-aae4f000-ae05-11e8-9751-85a234465066.png">

After window is moved:
<img width="708" alt="screenshot 2018-09-01 at 16 38 53" src="https://user-images.githubusercontent.com/1478221/44947497-aae4f000-ae05-11e8-8efd-e02bbc43f70c.png">

I realise Mojave is a beta OS - I wouldn't be surprised if it's entirely an issue with the OS rather than gosu - but I'm obviously not sure.

**Comment by jlnr** [comment]
Oh no. I actually had a Mojave partition for testing, but I nuked it because it was too buggy for daily use.

I'll try installing Mojave again after I've finished everything else on the list for 0.14.0. Please let me know if the issue goes away in the meantime.

**Comment by Dan2552** [comment]
👍 will do

in the meantime I made a little hack using apple script:

``` osascript
#!/usr/bin/env osascript

delay 1

tell application "System Events"
    set the props to get the properties of the front window of application process "ruby"
    set theSBounds to position of props
    set theSBounds to {(item 1 of theSBounds) + 1, item 2 of theSBounds}
    set position of front window of application process "ruby" to {item 1 of theSBounds, item 2 of theSBounds}
end tell
```

**Comment by jlnr** [comment]
Not sure if it's any consolation, but `brew install supertux` has the same problem.

**Comment by Dan2552** [comment]
https://twitter.com/icculus/status/1045106686573400064?s=21

**Comment by jlnr** [comment]
Thanks, good to hear. I'll kick my little hack out as soon as SDL 2.0.9 lands.
