### ISSUE TITLE
Distinguish between different sticks and pads on gamepads

### ISSUE THREAD

**Issue by taras-dashkevich** [gosu/gosu#467]
Currently left pad and all sticks using same constants:
- Gosu::GpLeft
- Gosu::GpRight
- Gosu::GpUp
- Gosu::Down

Would be nice to have separately and for sticks additional method  returns vluae (for example -1..1)

Thanks

**Comment by jlnr** [comment]
I've renamed this ticket because a feature request for analog stick inputs already exists (#412). The issue in this ticket is that all sticks and pads are mapped to the same four constants. It's likely that both issues will be closed with the same patch, though.

**Comment by Tetssuwan** [comment]
Thanks @jlnr

**Comment by jlnr** [comment]
Fixed in #524
