### ISSUE TITLE
Documentation on rubydoc.info is outdated

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu#470]
This page still has not been updated with the changed interface in Gosu 0.14.x:

https://www.rubydoc.info/github/gosu/gosu/master/Gosu/Font

Not sure what to do about this.

Thanks to JetPirate on Discord for bringing this to my attention.

**Comment by JetPirate** [comment]
I guess all the docs should be updated. Not just Font page. I didn't find anything about Gosu.render method which was mentioned on Discord several times.

**Comment by jlnr** [comment]
I have recently force-pushed a few things to Gosu's master branch. I wonder if the rubydoc.info box now has my repo stuck in an invalid state?

https://github.com/docmeta/rubydoc.info/blob/master/lib/scm_checkout.rb#L137-L139

Does `git pull --force` recover from stuff like that? I wonder if the code shouldn't fetch and checkout instead.

**Comment by pmer** [comment]
They shouldn’t be pulling for exactly this reason. I’d hope they were fetching and then hard resetting to the remote’s (GitHub’s) head.

**Comment by jlnr** [comment]
https://github.com/docmeta/rubydoc.info/issues/130
