### ISSUE TITLE
Could not initialize SDL Video: No available video device

### ISSUE THREAD

**Issue by cyoce** [gosu/gosu#473]
When I try to run the first example project in the wiki, I get ``/var/lib/gems/2.5.0/gems/gosu-0.14.4/lib/gosu/swig_patches.rb:17:in `initialize': Could not initialize SDL Video: No available video device (RuntimeError)``. 

I tried Googling the error, but everything I found was completely unhelpful and/or specific to something other than Gosu/Ruby

I'm sure I'm missing something obvious, but I'm stumped. Hopefully someone on here can help?

**Comment by jlnr** [comment]
I assume from the path that you are using Linux. Is this on an ARM computer like the Raspberry Pi, or on a 'normal' PC? Do other OpenGL games work, say SuperTux?

**Comment by cyoce** [comment]
@jlnr I'm on a normal Windows 10 computer using the Windows Subsystem for Linux (Ubuntu). OpenGL games have worked on my computer.

**Comment by jlnr** [comment]
Ah, I see. Do OpenGL games work through WSL? I recommend using the standard Windows version of Ruby instead. Closing this because WSL is out of scope for Gosu.
