### ISSUE TITLE
A has_point method?

### ISSUE THREAD

**Issue by SavageHolycow** [gosu/gosu#474]
In Godot the has_point method is really handy and make things easier. Can we get a method like that?

**Comment by jlnr** [comment]
This is out of scope for Gosu. There is no single good way to design geometry primitives, either. Should they be mutable or immutable? Should floating point values be allowed, or only integer values? What about negative sizes?

Maybe there are other libraries for this ([this looks like one?](https://www.rubydoc.info/gems/geometry/6.5/)).
