### ISSUE TITLE
Gosu::Color should implement Gosu::Color#argb

### ISSUE THREAD

**Issue by mblumtritt** [gosu/gosu#476]
Since `Gosu::Color.new` accepts an argb value the instance should be able to return this value.

A method `Gosu::Color#argb` would be fine, maybe `Gosu::Color#to_i` is acceptable for this.

There is only an `Gosu::Color#abgr` which is not accepted by any `Gosu::Color` method. (Where is this helpful?)

**Comment by jlnr** [comment]
In theory there is a `Gosu::Color#argb` method, but in practice SWIG has merged it with the class method of the same name:

```
irb(main):004:0> Gosu::Color.argb
ArgumentError (Wrong arguments for overloaded method 'Color.argb'.)
Possible C/C++ prototypes are:
    std::uint32_t Color.argb(Gosu::Color const *self)
    Gosu::Color Color.argb(Gosu::Color::Channel a, Gosu::Color::Channel r, Gosu::Color::Channel g, Gosu::Color::Channel b)
    Gosu::Color Color.argb(std::uint32_t argb)
```

I'll export it in SWIG as `#to_i` to prevent this from happening, and then alias it to `#argb` as well.

> There is only an Gosu::Color#abgr which is not accepted by any Gosu::Color method. (Where is this helpful?)

I think this is from when Gosu still had a Direct3D backend. There's also a `#bgr` method that I think was only ever useful for Win32 programming:

```
irb(main):006:0> Gosu::Color::FUCHSIA.bgr
=> 16711935
```

Maybe I'll kick them out at some point in the future.
