### ISSUE TITLE
image_draw scale_x does not seem to work

### ISSUE THREAD

**Issue by Chuckatmaine** [gosu/gosu#477]
Trying to dynamically scale an image but scale_x does not seem to actually change the height scale while scale_y does change the width scale.  Am I doing something wrong or do I just not understand the intent of scale_x? 
@image.draw(@x, @y, scale_x = 2, scale_y = 2, 1)
  Windows 10.
gosu (0.14.4 x64-mingw32, 0.14.0 x64-mingw32, 0.13.3 x64-mingw32)
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]

**Comment by jlnr** [comment]
The third parameter in `Image#draw` is always the Z position, so it should work if you use `@image.draw(@x, @y, 1, 2, 2)` instead. Gosu does not use named arguments, so what's happening in your call is that you initialize two variables `scale_x` and `scale_y` to 2, and then pass these values as the arguments for `z` and `scale_x`.

This comes up a lot, and Gosu will probably start using named arguments soon, which will make the order of parameters much less important. (#443)
