### ISSUE TITLE
Add retro option to Font

### ISSUE THREAD

**Issue by cyberarm** [gosu/gosu#479]
![example](https://user-images.githubusercontent.com/581879/48959408-bfc7b000-ef2a-11e8-97b6-a3e09cf176a2.png)
Left: Non-retro
Right: Desired-ish result with retro

**Comment by jlnr** [comment]
I have vague plans to solve this in a more generic way, namely, by passing a block to Font.new that is responsible for rendering characters into a Gosu::Image. That way, you could override some characters by loading them from files (e.g. Emoji), you could use `retro: true` to render them (I'm not sure if that's already possible with Image.from_text), etc.

**Comment by fguillen** [comment]
I am also missing this :+1

**Comment by jlnr** [comment]
Fixed in #624
