### ISSUE TITLE
Difficulty installing Gosy

### ISSUE THREAD

**Issue by LWFlouisa** [gosu/gosu#482]
https://github.com/gosu/gosu/wiki/Getting-Started-on-Linux
checking for main() in -lopenal... no
creating Makefile

current directory: /var/lib/gems/2.3.0/gems/gosu-0.14.4/ext/gosu
make "DESTDIR=" clean

current directory: /var/lib/gems/2.3.0/gems/gosu-0.14.4/ext/gosu
make "DESTDIR="
compiling ../../src/Audio.cpp
In file included from ../../src/Audio.cpp:1:0:
../../src/AudioImpl.hpp:9:19: fatal error: AL/al.h: No such file or directory
compilation terminated.
Makefile:231: recipe for target 'Audio.o' failed
make: *** [Audio.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.3.0/gems/gosu-0.14.4 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/gosu-0.14.4/gem_make.out

**Comment by jlnr** [comment]
Did you follow the instructions in the link in the first line?

**Comment by LWFlouisa** [comment]
Yea figured it out, thanks!
