### ISSUE TITLE
Expected argument 0 of type Gosu::Window const *, but got X

### ISSUE THREAD

**Issue by nicholasrobertm** [gosu/gosu#483]
Running into an odd issue with a new game I'm working on.

When trying to reference the window width (or the window in general) I get the below exception.

`/home/rob/Projects/Appname/lib/entities/background_entity.rb:5:in 'width': Expected argument 0 of type Gosu::Window const *, but got App #<App:0x005621846c3490 @__swig... (ObjectPreviouslyDeleted)
	in SWIG method 'width'`

The game is ran via this line in my app.rb file (as I've done in the past which always worked fine):
`a = App.new.show`

The window is then passed to a scene which creates the background_entity.rb (and passes the window to it) with this line:
`@start_scene = StartScene.new(self)` 

'Self' in this case being the app which inherits from Gosu::Window via:
`class App < Gosu::Window`

Am I missing something here? 

Here is my bundler file:
```
GEM
  remote: https://rubygems.org/
  specs:
    gosu (0.14.5)

PLATFORMS
  ruby

DEPENDENCIES
  gosu

BUNDLED WITH
   2.0.1
```

And ruby version:
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`

Happy to provide any further info if needed! Also thanks for the great library!

<sup>Edited by @Kjarrigan - fixed the gem code block</sup>

**Comment by Kjarrigan** [comment]
@nicholasrobertm Can you please share a full example of what you are doing. As far as I have understand you do this?

```ruby
require 'gosu'

class MyScene
  def initialize(window)
    puts window.width
  end
end

class App < Gosu::Window
  def initialize
    super(480, 360)

    @ms = MyScene.new(self)
  end
end

App.new.show
```

Which works fine for me.

**Comment by jlnr** [comment]
I think I have seen errors like this when I forgot to call `super` in the constructor.

**Comment by nicholasrobertm** [comment]
Hey both, thanks for the help!

That looks almost identical to my setup, minus things being in separate ruby files.

`
require 'gosu'
require_relative 'lib/config'
require_relative 'lib/scenes/start_scene'
class App < Gosu::Window
  def initialize
    @game_config = Config.new('game', 'configs/game.yaml')
    @game_config.load_config
    resolution = @game_config.config['resolution']
    @start_scene = StartScene.new(self, resolution)
    super(resolution.split('x')[0].to_i,resolution.split('x')[1].to_i,fullscreen: @game_config.config['fullscreen'] || false)
  end

  def update
    @start_scene.update
  end

  def draw
    @start_scene.draw
  end

  def button_down(id)
    @start_scene.button_down(id)
  end

  def button_up(id)
    @start_scene.button_up(id)
  end

  def needs_cursor?
    true
  end

end

a = App.new.show
`
The paremeters are loading the values from a yaml file which are:
resolution.split('x')[0].to_i - 800
resolution.split('x')[1].to_i - 600
fullscreen: @game_config.config['fullscreen'] || false - false

Start Scene is a basic barebones scene:
`require_relative 'scene'
require_relative '../../lib/entities/background_entity'
require 'securerandom'
class StartScene < Scene
  def initialize(window, resolution)
    super(window, 'START')
    @entities << BackgroundEntity.new(SecureRandom.uuid, 'assets/background.jpg', resolution, 0, 0, 0)
  end

  def update
    @entities.each(&:update)
  end

  def draw
    @entities.each(&:draw)
  end

  def button_up(id)

  end

  def button_down(id)

  end
end`

And the contents of Scene:
`require 'gosu'
class Scene

  attr_reader :window, :name
  attr_accessor :entities


  def initialize(window, name)
    @window = window
    @name = name
    @entities = []
  end

  def update
    raise 'update should be an implemented method'
  end

  def draw
    raise 'draw should be an implemented method'
  end

  def button_down(id)
    raise 'button_down should be an implemented method'
  end

  def button_up(id)
    raise 'button_up should be an implemented method'
  end
end`

Appreciate any help!

**Comment by jlnr** [comment]
I haven't had a chance to run the code yet, but this shouldn't work:

`a = App.new.show`

The result of `show` is always `nil` (I think), so you need two lines - one to assign `a`, one to call `show`.

**Comment by nicholasrobertm** [comment]
It actually does work, since I don't care what the result of `a` is, I've switched it to:
```
a = App.new
a.show
```
Though and seeing the same, I'm trying to make a smaller demo to replicate the issue

**Comment by jlnr** [comment]
Since a workaround has been found, I'm closing this.
