### ISSUE TITLE
Add Animation FEATURE

### ISSUE THREAD

**Issue by Nifriz** [gosu/gosu#489]
Hi,
I think would be a good idea, add somenthing to manage tiled image.

I have made this little class, to manage tiled image:

```
# Manage tiled image with animation
class Sprite
  attr_writer :offset

  def initialize(animation, time = 500, frames: 0, offset: 0)
    @animation = animation
    @time = time

    if frames.zero?
      @frames = @animation.size
      @offset = 0
    else
      @frames = frames
      @offset = offset
    end
  end

  def new_tiles(frames, offset = 0)
    @frames = frames
    @offset = offset
  end

  def draw(c_x, c_y, c_z)
    img = @animation[Gosu.milliseconds / @time % @frames + @offset]
    img.draw(c_x, c_y, c_z)
  end
end

````
And this is an example where I use it in a simple RPG (to make a moving character)

Inizialize:
`      @image = Sprite.new(Gosu::Image.load_tiles('character.png', ZOrdinals::FIELD_SIDE, ZOrdinals::FIELD_SIDE, tileable: true), frames: 3)
`

When I move it, i have only to change my frame offset (because every animation have the same number of frames)

```
  def down
     ...
      @image.offset = 0
    end

    def left
      ...
      @image.offset = 3
    end
```

**Comment by Kjarrigan** [comment]
Don't know about @jlnr, but you're code is really "short" so it seems pretty easy to do what you want to do and thus I'm against implementing it in gosu directly. Currently `gosu` only provides the basic tools and not really an convenience-overlay as there are multiple ways to do things and depending on your use-case on or the other might be better. The basic tools are hard enough to maintain as is. So :-1: from me.

One personal opinion about your code:

```ruby
  def draw(c_x, c_y, c_z)
    img = @animation[Gosu.milliseconds / @time % @frames + @offset]
    img.draw(c_x, c_y, c_z)
  end
```
I personally do the image switching in the `update`-method, as for me it is logic. The `draw` should only do the actual drawing and no calculations (in my eyes).

_Besides - if you ever have a version of your game you want to share post it in our [Showcase](https://www.libgosu.org/cgi-bin/mwf/board_show.pl?bid=2) or on [Reddit](https://www.reddit.com/r/gosu/). It's always nice to see what other people do._

**Comment by Nifriz** [comment]
I'm agree about move the calculation to `update` method.

About implementation I think can be useful, other gems like `ruby2d` offers good way to manage sprite animation, but at the same time I understand perfectly your opinion.

**Comment by jlnr** [comment]
I have no strong opinion on whether animations should go in `draw` or `update`, but @Kjarrigan is definitely right that this is beyond the scope of Gosu. Thanks for the suggestion though!
