### ISSUE TITLE
Discord invite link is invalid

### ISSUE THREAD

**Issue by AaronC81** [gosu/gosu#491]
The Discord invite link on the README doesn't seem to work, saying that the invite link is invalid:

![image](https://user-images.githubusercontent.com/3321773/54865315-9fcebe80-4d5b-11e9-8615-d8975425f966.png)
 
The link has probably expired and needs to be recreated.

**Comment by jlnr** [comment]
Good catch! Thanks. I've just checked the link on the libgosu.org homepage as well, but that one still seems to work.
