### ISSUE TITLE
Gosu::gl doesn't allow a nil parameter (against rdoc specification)

### ISSUE THREAD

**Issue by bestguigui** [gosu/gosu#493]
Hi ! Gosu::gl does only allow to set some Z value or **nothing**. It's not possible to set some _nil_ value, even if it's specified as default on the rdoc.

We got the error : Wrong arguments for overloaded method 'unsafe_gl'.

**Comment by Kjarrigan** [comment]
I assume you do something like this?
```ruby
z = nil
gl(z) do
# Do stuff
end
```
Because this should work:
```ruby
gl do
# Do stuff
end
```

I think this is a SWIG thing because it generates two methods with and without and args but the version with args doesn't allow to set it to nil:
```c
    void unsafe_gl()
    {
        Gosu::Graphics::gl([] { rb_yield(Qnil); });
    }
    
    void unsafe_gl(Gosu::ZPos z)
    {
        VALUE block = rb_block_proc();
        Gosu::Graphics::gl(z, [block] {
            Gosu::call_ruby_block(block);
        });
    }
```

So maybe we can add an compat wrapper like this:

```
def gl(z=nil, &block)
  return super(&block) if z.nil?

  super(z, &block)
end
```

**Comment by jlnr** [comment]
There's already a compat wrapper (sort of) in `swig_patches.rb`, it only needs to be extended to call the no-arg version for `z == nil`.
