### ISSUE TITLE
Resizable in Linux (Kubuntu 19.04)

### ISSUE THREAD

**Issue by betam4x** [gosu/gosu#498]
Is there no way to make the game window resizable for Linux users?  I can't seem to figure out how to get it to work.  Setting resizable to true does nothing for me.

**Comment by 513ry** [comment]
I experience the same on Debian. Well, there is a way, use Tk window. c:

siery

>> Sent: Friday, May 24, 2019 at 11:28 PM
>> From: "betam4x" <notifications@github.com>
>> To: gosu/gosu <gosu@noreply.github.com>
>> Cc: Subscribed <subscribed@noreply.github.com>
>> Subject: [gosu/gosu] Resizable in Linux (Kubuntu 19.04) (#498)
>> Is there no way to make the game window resizable for Linux users? I can't seem to figure out how to get it to work. Setting resizable to >> >> true does nothing for me.

**Comment by jlnr** [comment]
No version that supports `resizable: true` has been released yet. If you want to give it a try, you'll have to compile from source, see https://github.com/gosu/gosu/wiki/Hacking-Gosu. If you want you can also look into fixing #497 on the way 😎

**Comment by jlnr** [comment]
Closing this as support for resizable windows has been available for two versions or so now.
