### ISSUE TITLE
suddenly cant find file? (update issue?)

### ISSUE THREAD

**Issue by abw1996** [gosu/gosu#505]
`/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': libGL.so.1: cannot open shared object file: No such file or directory - /var/lib/gems/2.3.0/gems/gosu-0.14.5/lib/gosu.so (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /var/lib/gems/2.3.0/gems/gosu-0.14.5/lib/gosu.rb:25:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from theAdventuresOfStickly.rb:2:in `<main>'`

everything was going great and then one day this popped up. check the directory and everything is still there like its been up till now. any advice. (linux 64)

**Comment by jlnr** [comment]
Has your libGL moved through some external package update? Reinstalling Gosu might help: `gem uninstall gosu && gem install gosu`.

**Comment by abw1996** [comment]
I have uninstalled gosu and when i tried to reinstall it there was issues with the supporting packages so i tried reinstalling them and i got this

Package libglvnd-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libglvnd-dev' has no installation candidate

also thanks for the help mate :)

**Comment by jlnr** [comment]
That "E: Package 'libglvnd-dev' has no installation candidate" seems to be the googleable part of this error message. Good luck fixing this, I just went through similar errors on one of my machines :) This is out of scope for this repository though.
