### ISSUE TITLE
Gosu::layout_text crashes when running text tests

### ISSUE THREAD

**Issue by cyberarm** [gosu/gosu#509]
When using `Gosu::Image.from_text` in my ffi-gosu project, which used `Gosu::layout_text` instead of `Gosu::layout_markup`, gosu crashes.

```text
TextBuilder.cpp:45: void Gosu::TextBuilder::flush_current_line(Gosu::TextBuilder::EndOfLineReason): Assertion '!current_line.empty()' failed.
```
https://github.com/gosu/gosu/blob/cc72ffdfe53ece2ce3ba503b72d919156f109c30/src/TextBuilder.cpp#L44-L46

Triggered by:
https://github.com/gosu/gosu/blob/cc72ffdfe53ece2ce3ba503b72d919156f109c30/test/test_text.rb#L13

**Comment by jlnr** [comment]
Interesting. I wonder if this is broken on all platforms, but because `assert` is not compiled for Ruby extensions, nobody has noticed 😅
