### ISSUE TITLE
Error installing Gosu on Ubuntu

### ISSUE THREAD

**Issue by dcts** [gosu/gosu#514]
Getting the following error when attempting to install the Gosu gem on Ubuntu. I have already installed the dependencies. Here is the error message
```bash
compilation terminated.
Makefile:233: recipe for target 'TrueTypeFontUnix.o' failed
make: *** [TrueTypeFontUnix.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/dcts/.rvm/gems/ruby-2.5.5/gems/gosu-0.14.5 for inspection.
Results logged to /home/dcts/.rvm/gems/ruby-2.5.5/extensions/x86_64-linux/2.5.0/gosu-0.14.5/gem_make.out
```

my ruby version is 
```
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```

Any help is appreciated!

**Comment by jlnr** [comment]
Can you please try `sudo apt-get install libfontconfig1-dev` and then Gosu again? I think this package was missing from the dependencies on the Wiki page.

If that does not fix the error, please copy the complete output of `gem install gosu` into this issue. The compilation error is typically somewhere above the Makefile error, and starts with "error: ...".

**Comment by dcts** [comment]
jep that was it! Thanks a lot :)
