### ISSUE TITLE
Docs: `View on Github` links are broken

### ISSUE THREAD

**Issue by thiagojobson** [gosu/gosu#516]
The `view on Github` links in [documentation ](https://www.rubydoc.info/github/gosu/gosu/Gosu/) are broken. They lead to a 404 page.
An example, from `Gosu::Image.draw` documentation:

The actual link:
https://github.com/gosu/gosu/blob/Gosu/rdoc/gosu.rb#L436

The expected link:
https://github.com/gosu/gosu/blob/master/rdoc/gosu.rb#L436

**Comment by jlnr** [comment]
I just went to libgosu.org, then followed the link to the "Ruby Reference" in the right sidebar, and the links are working for me. Do you maybe have an outdated bookmark for the documentation?

The GitHub links are not super helpful anyway because all the interesting stuff happens in C++ :)
