### ISSUE TITLE
Add Window#resizable=

### ISSUE THREAD

**Issue by Fulgurance** [gosu/gosu#525]
Hello, in first, thanks for your work.

I have request. Can you add some functions into Gosu to resize, set fullscreen and change resizable state after window is made please ? There aren't any method to do that... Thanks you very much

**Comment by jlnr** [comment]
You can use `w.width = 800`, `w.height = 600`, and `w.fullscreen = false` to toggle these during runtime.

`Window#resizable=` is still missing as far as I can remember. SDL 2 supports it, and Gosu should follow suit: https://wiki.libsdl.org/SDL_SetWindowResizable

**Comment by Fulgurance** [comment]
I have already tested it, but when i do that, window's size don't change.

Look, i have tested  with simple example:

` 
require 'gosu'

class Tutorial < Gosu::Window
  def initialize
    super 640, 480
    self.caption = "Tutorial Game"
  end
  
  def update
    # ...
  end
  
  def draw
    # ...
  end
end

test = Tutorial.new.show
test.width = 320
test.height = 240
test.update
`

**Comment by jlnr** [comment]
Gosu has no supported for loading animated GIFs right now. If you think that it should support it, please open a separate ticket. I will use this ticket as a reminder to add the resizable setter.

The code above does not work for several reasons:
* The .show method only returns _after the window has been closed_. You must resize the window before calling show (which has the same effect as setting the constructor values), or you must resize the window in reaction to one of the callbacks (typically button_down if the user clicks on a resolution picker, or something like that).
* The .show method returns `nil`, not the window. Your variable `test` will be nil, and you should see exceptions in the output as soon as you close the window.
* You shouldn't call the update method from the outside, Window#show calls it internally in a loop (which is why Window#show doesn't immediately return - it's a loop).

**Comment by Fulgurance** [comment]
Oh okay, i try that now. Thanks

If you can yes plz for GIF.

**Comment by jlnr** [comment]
Yes, here is a short example:

```ruby
require "gosu"

class MyWindow < Gosu::Window
  def initialize
    super 800, 600, fullscreen: false
  end

  def needs_cursor?; true; end

  def button_down(id)
    case id
    when Gosu::MS_LEFT
      self.width, self.height = self.height, self.width
    when Gosu::MS_RIGHT
      self.fullscreen = !self.fullscreen?
    when Gosu::KB_ESCAPE
      close
    end
  end
end

MyWindow.new.show
```

Left-click to rotate the window (swap width and height), right-click to toggle fullscreen mode.

**Comment by Fulgurance** [comment]
Okay, it's good, i have understand :)

Just little question, when i try to use Image class, i have this error, why ?

`Traceback (most recent call last):
        7: from Main.rb:50:in `<main>'
        6: from Game.rb:91:in `Start'
        5: from /home/zohran/.gem/ruby/2.7.0/gems/gosu-0.15.1/lib/gosu/patches.rb:78:in `tick'
        4: from /home/zohran/.gem/ruby/2.7.0/gems/gosu-0.15.1/lib/gosu/patches.rb:78:in `tick'
        3: from Game.rb:35:in `update'
        2: from Introduction.rb:15:in `Start'
        1: from Sprite.rb:41:in `Draw'
Sprite.rb:41:in `draw': There is no rendering queue for this operation (RuntimeError)`

(Sprite inherit to Image class)

**Comment by jlnr** [comment]
You cannot call any draw* method except from within Window#draw. Rendering in Gosu is not permanent, you are not writing to a bitmap, but instead the window redraws everything at (typically) 60 frames per second. You'll need to separate the initialization logic from the rendering, and call the rendering from Window#draw.

Glad to hear that the resizing worked! Closing this issue.

**Comment by Fulgurance** [comment]
Thanks for your reply, it's okay ! After i have understand it :) I have overwrited my class

**Comment by jlnr** [comment]
(Reopening because I just realized that the window.resizable setter is still missing)

**Comment by Fulgurance** [comment]
Sorry, but i have again problem. Before, my code work, but now, when i start my game, i have window, but my code don't play my sound and show any graphics. I have updated some part of my code, but i don't found the source of problem...

Look:
Main
```
require 'gosu'

load 'Input.rb'
load 'SpriteColor.rb'
load 'Sprite.rb'
load 'Text.rb'
load 'Audio.rb'
load 'Scene.rb'

load 'Thing.rb'
load 'Condition.rb'
load 'Effect.rb'

load 'AlternateForm.rb'
load 'BodyShape.rb'
load 'Color.rb'
load 'EggGroup.rb'
load 'EvolutionCondition.rb'
load 'ExperienceGroup.rb'
load 'MoveLearningCondition.rb'

load 'MoveInformation.rb'
load 'Move.rb'
load 'AbilityInformation.rb'
load 'Ability.rb'

load 'EvolutionsInformation.rb'
load 'AptitudesInformation.rb'
load 'ExperienceInformation.rb'
load 'GivenEVInformation.rb'
load 'StatisticsInformation.rb'
load 'SexualityInformation.rb'
load 'BodyInformation.rb'
load 'BaseInformation.rb'
load 'PokemonInformation.rb'
load 'Pokemon.rb'

load 'PokemonTeam.rb'
load 'ItemCategory.rb'
load 'ItemInformation.rb'
load 'BagItem.rb'
load 'BagPocket.rb'
load 'Bag.rb'
load 'Badge.rb'
load 'Player.rb'

load 'IntroductionCredits.rb'
load 'Game.rb'

$Game = Game.new
$Game.Start
```
Game
```
class Game < Gosu::Window
    
    @@DefaultWindowTitle = "Jeu"
    @@DefaultWindowWidth = 800
    @@DefaultWindowHeight = 500
    @@DefaultWindowFullScreen = false
    @@DefaultWindowResizable = false
    @@DefaultWindowUpdateInterval = 16.666666
    @@DefaultPressedKey = 0
            
    attr_reader:Introduction
    attr_accessor:GenerateNumber
    attr_accessor:GetWindowTitle
    attr_accessor:SetWindowTitle
    attr_accessor:GetWindowWidth
    attr_accessor:SetWindowWidth
    attr_accessor:GetWindowHeight
    attr_accessor:SetWindowHeight
    attr_accessor:GetWindowFullScreen
    attr_accessor:SetWindowFullScreen
    attr_accessor:GetWindowResizable
    attr_accessor:SetWindowResizable
    attr_accessor:GetWindowUpdateInterval
    attr_accessor:SetWindowUpdateInterval
    attr_accessor:ResizeWindow
    attr_accessor:PressedKey
    
    def initialize(title = @@DefaultWindowTitle, width = @@DefaultWindowWidth, height = @@DefaultWindowHeight, fullscreen = @@DefaultWindowFullScreen, resizable = @@DefaultWindowResizable, updateInterval = @@DefaultWindowUpdateInterval)
       super(width, height, fullscreen, resizable, updateInterval)
       self.caption = title
       self.show
       $Scene = IntroductionCredits.new
    end

    def update
        if $Scene != nil
            $Scene.Update
        end
    end
    
    def draw
        if $Scene != nil
            $Scene.Draw
        end
    end
    
    def GenerateNumber(firstNumber, secondNumber)
        return self.random(firstNumber, secondNumber)
    end
    
    def GetWindowTitle
        return self.caption
    end
    
    def SetWindowTitle(title = @@DefaultWindowTitle)
        self.caption = title
    end    
        
    def GetWindowWidth
        return self.width
    end
    
    def SetWindowWidth(width = @@DefaultWindowWidth)
        self.width = width
    end
    
    def GetWindowHeight
        return self.height
    end
    
    def SetWindowHeight(height = @@DefaultWindowHeight)
        self.height = height
    end
    
    def GetWindowFullScreen
        return self.fullscreen
    end
    
    def SetWindowFullScreen(fullscreen = @@DefaultWindowFullScreen)
        self.fullscreen = fullscreen
    end
    
    def GetWindowResizable
        return self.resizable
    end
    
    def SetWindowResizable(resizable = @@DefaultWindowResizable)
        self.resizable = resizable
    end
    
    def GetWindowUpdateInterval
        return self.update_interval
    end
    
    def SetWindowUpdateInterval(updateInterval = @@DefaultWindowUpdateInterval)
        self.update_interval = updateInterval
    end
    
    def ResizeWindow(width = @@DefaultWindowWidth, height = @@DefaultWindowHeight)
        self.width = width
        self.height = height
    end
    
    def PressedKey(pressedKey = @@DefaultPressedKey)
        return self.button_down? @@DefaultPressedKey
    end
        
end

```
```
Introduction
class IntroductionCredits < Scene
    
    attr_reader:Time
    attr_reader:CreditDuration
    attr_reader:Credits
    attr_reader:CreditsColor
    attr_reader:CreditsText
    attr_reader:CreditsSound
    
    def initialize
       @Time = 0
       @CreditDuration = 120
       @Credits = Sprite.new("Sprites/CreditsIntroduction.png", 0, 0, 0, 1, 1)
       @Credits.SetX = 0
       @Credits.SetY = 0
       @Credits.SetZ = 0
       @CreditsColor = SpriteColor.new(255,255,255,255)
       @CreditsText = Text.new("Fulgurance present", "Fonts/PokemonDS.ttf", 14, @CreditsColor, $Game.GetWindowWidth/2-@CreditsText.GetWidth/2, $Game.GetWindowHeight/2-@CreditsText.GetHeight/2, 1)
       @CreditsSound = Audio.new("Sounds/GameStart.mp3")
       @CreditsSound.Play
    end
    
    def Update
        if @Time < @CreditDuration
            @Time += 1
        end
            
        if $Game.PressedKey(Input::ENTER) && @Time >= @CreditDuration
            
        end
        
        if $Scene != self
            @Credits = nil
            @CreditsColor = nil
            @CreditsText = nil
        end
    end
    
    def Draw
        @Credits.Draw
        @CreditsText.Draw
    end
    
end

```
I think when i have change some part i have doing something bad, but i'm tired and i don't found the problem ...
