### ISSUE TITLE
Problem with OpenGL

### ISSUE THREAD

**Issue by Fulgurance** [gosu/gosu#529]
Hello, today i would like to test OpenGL integration for Gosu, i have installed opengl, gl, glu, glut and ruby-opengl gems, but i have an error when i try to start opengl code example:

```
Traceback (most recent call last):
        6: from Main.rb:60:in `<main>'
        5: from Main.rb:60:in `new'
        4: from Game.rb:28:in `initialize'
        3: from /home/zohran/.gem/ruby/2.7.0/gems/gosu-0.15.1/lib/gosu/patches.rb:78:in `tick'
        2: from /home/zohran/.gem/ruby/2.7.0/gems/gosu-0.15.1/lib/gosu/patches.rb:78:in `tick'
        1: from Game.rb:39:in `draw'
Scene3D.rb:8:in `Draw': undefined method `gl' for #<Scene3D:0x000055dd7e8618f0> (NoMethodError)
```

And just little question, what is the lastest opengl supported version by Gosu ?

**Comment by jlnr** [comment]
I am not sure which OpenGL gem works the best right now, but it seems like you are looking for the Gosu.gl method and calling it in a context where it cannot be found by just typing "gl". Try Gosu.gl and see if that works.

> And just little question, what is the lastest opengl supported version by Gosu ?

Gosu tells SDL2 to open a window that supports OpenGL (SDL_WINDOW_OPENGL). I'm not sure if that defaults to the lowest or highest version - I guess it's up to you to find out, I only know the older standards, so never noticed anything that's missing.

**Comment by Fulgurance** [comment]
I have added include Gosu directive, but the same error...

**Comment by jlnr** [comment]
Including only makes classes and constants available, not methods. Gosu.gl will always work and is the preferred way to do this (the example game might be outdated).

**Comment by jlnr** [comment]
Disregard my previous answer, I don't know why `include Gosu` does not make `gl` available.

However, nowadays I would always recommend to prefix everything with Gosu:: or Gosu. over using `include Gosu`. The reason is that with the explicit module it is easier to implement deprecation messages for renamed classes using `const_missing`.

**Comment by Fulgurance** [comment]
Now, if i do that, i have `undefined method `GL_COLOR_BUFFER_BIT'`

**Comment by jlnr** [comment]
It might be as easy as the "gl" gems putting things into a module named "GL" or something.

Either way, it's outside of the scope of this repository, sorry. StackOverflow would be a better place for this.
