### ISSUE TITLE
Gems fails to install gosu

### ISSUE THREAD

**Issue by DavidTPerkins** [gosu/gosu#531]
I'm running on Max Catalina 10.15.4.  I've successfully installed various ruby gems, but when I install Gosu I get this error (sudo gem install gosu)

current directory: /usr/local/lib/ruby/gems/2.7.0/gems/gosu-0.15.1/ext/gosu
make "DESTDIR="
compiling ../../src/Audio.cpp
In file included from ../../src/Audio.cpp:1:
In file included from ../../src/AudioImpl.hpp:3:
In file included from ../../Gosu/Audio.hpp:7:
In file included from ../../Gosu/IO.hpp:6:
In file included from ../../Gosu/Platform.hpp:20:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:641:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:60:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
make: *** [Audio.o] Error 1

Any help, please.  Many thanks.

**Comment by jlnr** [comment]
Sorry, somehow this issue slipped through the cracks. I am on Catalina myself and haven't seen this bug. Not finding string.h sounds like a major issue. Can you please try uninstalling and reinstalling Xcode? And that the right toolchain is selected in the Xcode preferences?

<img width="912" alt="Bildschirmfoto 2020-07-04 um 11 02 32" src="https://user-images.githubusercontent.com/70772/86509113-f2fc4180-bde5-11ea-8d74-bea7074e57d7.png">

**Comment by jlnr** [comment]
Closing for now, if the problem persists, please post more details and I'll re-open it.
