### ISSUE TITLE
ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by lomitha** [gosu/gosu#549]
Hey all,
I was trying to install Gosu into my mac OS and this happened,

<img width="1440" alt="Screenshot 2020-10-21 at 13 10 37" src="https://user-images.githubusercontent.com/73186583/96688457-d25cf500-139e-11eb-8164-bf84625ecf16.png">

The version of ruby I have installed is, ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

Could anyone please tell me why and how to tackle it? Thanks very much.

**Comment by jlnr** [comment]
I'm a little confused by the error message. Why is it looking in MacOSX11.0.sdk? Are you on OS X 10.11 El Capitan? How did you install Ruby 2.6?

**Comment by lomitha** [comment]
Hey, 
I run on a MacOS catalina 10.15.7 (19H2)
I used homebrew to install ruby, $ brew install ruby
I m pretty new to this and hope this information is suffiecnt.
thank you and regards

**Comment by lomitha** [comment]
> I'm a little confused by the error message. Why is it looking in MacOSX11.0.sdk? Are you on OS X 10.11 El Capitan? How did you install Ruby 2.6?
Hey,
I run on a MacOS catalina 10.15.7 (19H2)
I used homebrew to install ruby, $ brew install ruby
I m pretty new to this and hope this information is suffiecnt.
thank you and regards

**Comment by lomitha** [comment]
Hey,
I run on a MacOS catalina 10.15.7 (19H2)
I used homebrew to install ruby, $ brew install ruby
I m pretty new to this and hope this information is suffiecnt.
thank you and regards

**Comment by jlnr** [comment]
If you are on macOS 10.15 (same as me), then I don't know why it is trying to build with such an ancient SDK; some macOS update probably didn't clean up properly.

What I suggest doing...
- [Uninstall the Command Line Tools](https://apple.stackexchange.com/a/310470) including the old 10.11 SDK
- Reinstall either the current version of the command line tools using `xcode-select --install`, or Xcode from the App Store
- Run `brew doctor` to see if Homebrew can use the compiler
- Retry installing Gosu

Does that work?

**Comment by jlnr** [comment]
Closing due to lack of feedback
