### ISSUE TITLE
Could not initialize SDL video error

### ISSUE THREAD

**Issue by mintyjones** [gosu/gosu#554]
I have been searching online for a solution to this problem when I try an initialize a window with gosu. I am running ruby through WSL. Is it maybe a problem with dependencies - I just can't seem to find much talk about this particular error.

```
Could not initialize SDL Video: No available video device (RuntimeError)
```

**Comment by cyberarm** [comment]
I've had this issue before when trying to use Gosu headless (without a display), does your WSL environment have a _display_?
You can try this: https://wiki.ubuntu.com/WSL#Running_Graphical_Applications
Or try searching: "wsl SDL: No available video device"

**Comment by mintyjones** [comment]
Thanks so much, @cyberarm! From that link you provided, I downloaded VcXsrv Windows X Server, ran it, and was suddenly able to initialise a window! That is very exciting!

**Comment by jlnr** [comment]
Thanks for the pointer @cyberarm! I've added a link to this issue to the Windows wiki page: https://github.com/gosu/gosu/wiki/Getting-Started-on-Windows
