### ISSUE TITLE
Prereleases present on RubyGems missing on Github

### ISSUE THREAD

**Issue by mensfeld** [gosu/gosu#570]
Hey there,

I noticed that there are 1.1.0.pre releases present on RG: https://rubygems.org/gems/gosu/versions that are missing here: https://github.com/gosu/gosu/releases 

Is that intended?

**Comment by jlnr** [comment]
I've released the pre gems from an unmerged PR for testing: https://github.com/gosu/gosu/pull/569

The commit that pre1 was built from has already been rewritten. Keeping the pre releases more informal also means the list of git tags will be more manageable.

If it helps, the final 1.1.0 gem will probably be out tonight, anyway :)

**Comment by mensfeld** [comment]
Wow what a fast reply @jlnr! Thank you :pray:
