### ISSUE TITLE
[Documentation / Wiki] The page https://github.com/gosu/gosu/wiki/Getting-Started-on-Linux - could it list upstream sources without specific distributions?

### ISSUE THREAD

**Issue by rubyFeedback** [gosu/gosu#574]
Hey gosu folks,

Have a look at the wiki here:

https://github.com/gosu/gosu/wiki/Getting-Started-on-Linux

It shows different methods on different distributions.

I don't use any of these distributions. I do, however had, use ruby to compile everything
I need on a LFS-like build.

Trying to compile the most recent gosu I run into this error:

CMake Error at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find OpenAL (missing: OPENAL_LIBRARY OPENAL_INCLUDE_DIR)

Ok I need OpenAL. But finding this is not trivial.

I have two candidates:

https://github.com/kcat/openal-soft/archive/openal-soft-1.21.0.tar.gz
http://www.openal.org/openal_webstf/downloads/openal-0.0.8.tar.gz

I assume it is actually openal-soft.

But anyway, my point ... could someone please add a "generic" list of
the upstream source code first, BEFORE describing the per-distribution
solution? Because the per-distribution solutions do not help me at all;
the generic way, though, would help me at once. The cmake-based
error messages often are not that useful either. :\

That is why it would help immensely if there could be a SHORT subsection
at the top that just briefly says which programs are required. You don't
have to supply any URL to the tarballs! I already have a ruby project that
handles this (it is available on rubygems too), but having to guess is a
bit harder than it ought to be IMO. That is why it would be great if 
someone could add this onto the wiki. Really just a very short drop-down
listing or so, bullets. (I never found out why openal-soft is openAl ...
weird name).

**Comment by rubyFeedback** [comment]
Another example just there (I solved the openal-soft situation above, it now compiles):

"-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) "

I tried to google for GTest, but I only found "Google Test". Cmake is really not that helpful. :(

meson is a bit better ... but this is an aside. It would help if the information is available
somewhere on the wiki page perhaps, because google search often leads to crappy results
too, especially for cryptic or multi-named projects such as GTest.

**Comment by jlnr** [comment]
GTest is Google Test. But if you plan to use Gosu with Ruby, you do not have to CMake at all. The "Hacking Gosu" wiki page is a bit outdated, but the instructions for building the Ruby gem are still up-to-date: https://github.com/gosu/gosu/wiki/Hacking-Gosu

**Comment by jlnr** [comment]
> But anyway, my point ... could someone please add a "generic" list of the upstream source code first, BEFORE describing the per-distribution solution?

I doubt that anyone has compiled this information before. For example, OpenAL and OpenGL are standardized APIs, Gosu doesn't care which specific implementation it is compiled and linked against. If you want to know what code Gosu uses on a typical Linux system, I suggest you look at the package list for any of the distributions, and look at the package metadata to see where its maintainers import the sources from.

If you want to add such a list to the wiki page, feel free to append this information to the wiki page. Just not at the top please, Ubuntu/Debian derivatives are the most common thing people would be looking for.

**Comment by jlnr** [comment]
Actually, I just realized that the top of the wiki page is trying to be what you are looking for (kind of):

> libsdl2-dev, libgl1-mesa-dev, libopenal-dev, libgmp-dev, libfontconfig1-dev

Gosu does not care which implementation of OpenAL you use, and I kind of forgot why Gosu needs libgmp (maybe it doesn't anymore?). If you want, you can replace these Debian-ish package names with even more generic names.
