### ISSUE TITLE
[API usage question for class Song] is it possible to specify backends for class Gosu::Song, e. g. specifically avoid pulseaudio to suppress a warning?

### ISSUE THREAD

**Issue by rubyFeedback** [gosu/gosu#577]
Hey there,

In the tetris-clone, it is playing an .ogg file.

When playing it, I get this message:

[ALSOFT] (WW) Failed to initialize backend "pulse"

The song works fine from how I can see (or rather hear) it.

I had a look here:

https://www.rubydoc.info/github/gosu/gosu/master/Gosu/Song

Is there any way we can customize this via class Song?

For example, perhaps I can just use some option hash and
say:

   Song.new("bla.ogg", backend: :alsa)

Or something like that, to avoid pulseaudio? (My oldschool
Linux system here is not using pulseaudio.)

Of course I do not know whether:

a) this is easily possible
b) this is wanted from an API design point of view

I understand both arguments against this by the way!

I am just wondering how much control we can have from gosu
in regards to audio-related data.

I also saw the old jukebox-example on the webforum, so
I eventually want to build a mini-player as well, via
gosu. :D (Needs some audio support ... by the way,
perhaps also being able to support ffmpeg+mpv; I think
I can get away with this, rather than using class Song
perhaps. Both ffmpeg and mpv are really nifty. Ideally,
though, as much functionality available within gosu
itself would be best, in particular for cross-platform
support.)

This issue can be closed I suppose, as it is more a question
than a suggestion for change, per se.

**Comment by jlnr** [comment]
Gosu basically just tells OpenAL to play audio using the default settings, and I don't want to make the interface more complicated.

I am not familiar with how al-soft works, but is there a way to either compile it without support for PulseAudio, or to configure its default output "device"? It would be better to fix the issue at this level.

However, one thing that I've learned about al-soft is that it has a tendency to print verbose log messages for no reason at all. As annoying as it is, maybe it's best to just ignore it. After all, when a game is finished, players will probably launch it through a .desktop file with no visible terminal.

(It's been a busy month, still going through notifications...)
