### ISSUE TITLE
Possibility to relocate/move/reposition Gosu::Window before .show / startup?

### ISSUE THREAD

**Issue by rubyFeedback** [gosu/gosu#578]
Hello gosu-devs, maintainers and users.

From ruby-gtk3 I am very used to the following:

    window = Gtk::Window.new
    window.move(0, 0)

The second line relocates the current main gtk-window
to the top-left position.

When I work with gosu, the window appears in the middle.

I have finally started to port some ruby-gtk3 games
to gosu; still very slow learning process, I am 
a noob but I did a "hello world" from scratch
finally. You can't imagine how hard it is to 
learn something new ... :P

I also found out how to use the Hack font! (Or at the
least that seems to work; need to test it). And
colours ... actually I may do another suggestion
in regards to colours lateron.

So back to the issue here:

- Would it be possible for gosu to get some API
where we could re-position the main (top) window
to some specific area of the screen? It does
not necessarily have to be .move(), although I
would not mind - same APIs. :D

I had a look at:

https://www.rubydoc.info/github/gosu/gosu/master/Gosu/Window

But we don't seem to be able to control at the least
the Gosu::Window interface there. If some API could
be added there that would be great.

**Comment by jlnr** [comment]
Hey. Thanks for the suggestion, but I have decided not to try to turn Gosu into a windowing toolkit (like GTK). It's just an endless rabbit hole full of decisions and cross-platform headaches. I'm going to close this issue, but am willing to reconsider if it there is a real use case for this in games. (SDL offers SetWindowPosition, so I guess it'd be technically possible.)
