### ISSUE TITLE
Gosu Verbosity or "extra helpfulness level" - toggled by the ruby user writing code

### ISSUE THREAD

**Issue by rubyFeedback** [gosu/gosu#581]
I have a suggestion for a new Warning or style of warnings. I have been writing
quite a bit of ruby-code specific to gosu ... already finished a hangman game :D
but ... I am using pure ASCII for now in a mono-spaced font, just to see how
things go. I haven't dabbled much into images yet. :P

I am currently playing a bit with Gosu and I think I noticed
something.

I used an "on-screen help" section, but initially my x and y values
for the "rectangle" were out of the gosu main window. So I did not
see anything and that confused me, as I could not tell where the
problem was.

That was an easy fix of course; just change the x and y value.

But I was also wondering ... what if Gosu could have some option
to warn the user about this? Something like "Gosu being very
user-friendly"?

Not everyone may need this, I understand, so it should perhaps
not be a default as such. But! What if it it could be an option
that we gosu users could toggle? Something similar in spirit
to the "did-you-mean-gem" where this would help facilitate
creating games in gosu. Something a bit similar to rubocop 
perhaps, just without a "strict", invasive setting, and more
a "provide more information". A bit of an extra debug-state.

How could this be implemented?

Well, perhaps this could be stored in a module, so it can be
layered over Gosu as such when the user sets an ENV variable
or calls some Api in Gosu like:

    Gosu.be_helpful
    Gosu.enable_help
    Gosu.enable_verbose_help
    Gosu.very_verbose
    Gosu.verbose = :full
    Gosu.verbose = :normal # This would be the default, so not handled.

Or something like that. The ENV variable could be

    GOSU_VERBOSE = 1

Anyway. These are just suggestions!

My idea here would be that in the above situation, Gosu could write
this:

    "Warning: the specified x (500) and y (600) values are outside the
    range of the main window (200, 300)."

Or something like this.

I am not sure if this is wanted or not; it depends on how low-level
Gosu should be, I suppose. Every decision has trade-offs so I understand
if Gosu itself is not changed. But I wanted to mention this at the
least.

The above is just one example. In some ways the deprecation-warnings
are in a similar spirit, as you encourage users to update their old
code base too. :)

(I am noticing lots of deprecation messages from older gosu projects
by the way. The help-module suggested above could also suggest 
replacements that could be copy/pasted as-is.)

PS: Actually perhaps a module is overkill, but it could be a per
method option, perhaps given via a block or so. { :verbose }
or anything like that.

**Comment by mblumtritt** [comment]
I don't like to see such testing code because it's common to have some parts outside of the screen (they may only partly visible).

Just play around with `Gosu.rotate` or `Gosu.scale` to get an idea what I mean… :)

**Comment by jlnr** [comment]
I agree with mblumtritt that drawing things off-screen is too common in games to warrant a warning.

In theory, Gosu already has a more verbose mode which is enabled by setting the GOSU_DEBUG variable. However, I'm not sure if it's really useful right now. Specific suggestions for additional log conditions are welcome.
