### ISSUE TITLE
Music stops too early

### ISSUE THREAD

**Issue by D3nX** [gosu/gosu#592]
My cousin and I when we were making some games using Gosu noticed that the music (when using Gosu::Song) stops approximatively ~1 second before the end of the song and it restart. It's a bit annoying, since seamless musics are cut of 1sec before the end and loop and as so it's not seamless anymore.

I don't know what is the origin that issue sadly, I just know it happens with Gosu::Song.

**Comment by OfficialPhilcomm** [comment]
Is there any update on this?

**Comment by jlnr** [comment]
I would recommend to subscribe to https://github.com/gosu/gosu/pull/562, although it's ridiculous how little time I've had for hobby coding this year, so please don't expect anything happening soon.

**Comment by jlnr** [comment]
Please retry, there were some changes in Gosu's audio dependencies. Maybe it was passively fixed by an update.

**Comment by D3nX** [comment]
No, I would even say worst, the looping became completely buggy, once the musics finishes to play (when using @song.play(true)) the music is becoming completely broken Oo

**Comment by cyberarm** [comment]
The looping glitches are probably related to #618 and should be mostly fixed by #619.

**Comment by jlnr** [comment]
@D3nX How is it with Gosu 1.4.1?

**Comment by jlnr** [comment]
I guess it is related to this issue, which I have already subscribed to but then forgot about https://github.com/icculus/SDL_sound/issues/27
