### ISSUE TITLE
ERROR:  Error installing gosu

### ISSUE THREAD

**Issue by almokhtarbr** [gosu/gosu#596]
# Setup: 
### Rbenv: 1.1.2

# Steps:
```brew install sdl2 libogg libvorbis```
```gem install gosu```

ERROR:  Error installing gosu: 	
ERROR: Failed to build gem native extension.
current directory: /Users/user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/gosu-1.2.0/ext/gosu
/Users/user/.rbenv/versions/2.7.3/bin/ruby -I /Users/user/.rbenv/versions/2.7.3/lib/ruby/2.7.0 -r ./siteconf20210627-1014-1doajwk.rb extconf.rb
The Gosu gem requires some libraries to be installed system-wide.
See the following site for a list:
https://github.com/gosu/gosu/wiki/Getting-Started-on-OS-X
creating Makefile

current directory: /Users/user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/gosu-1.2.0/ext/gosu
make "DESTDIR=" clean

current directory: /Users/user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/gosu-1.2.0/ext/gosu
make "DESTDIR="
compiling ../../src/Audio.cpp
compiling ../../src/AudioFileAudioToolbox.cpp
compiling ../../src/AudioFileSDLSound.cpp
compiling ../../src/AudioImpl.cpp
compiling ../../src/Bitmap.cpp
compiling ../../src/BitmapIO.cpp
compiling ../../src/BlockAllocator.cpp
compiling ../../src/Channel.cpp
compiling ../../src/Color.cpp
compiling ../../src/DirectoriesApple.cpp
compiling ../../src/DirectoriesUnix.cpp
compiling ../../src/DirectoriesWin.cpp
compiling ../../src/FileUnix.cpp
compiling ../../src/FileWin.cpp
compiling ../../src/Font.cpp
compiling ../../src/GosuGLView.cpp
compiling ../../src/GosuViewController.cpp
compiling ../../src/Graphics.cpp
compiling ../../src/IO.cpp
compiling ../../src/Image.cpp
compiling ../../src/Input.cpp
compiling ../../src/InputUIKit.cpp
compiling ../../src/Inspection.cpp
compiling ../../src/LargeImageData.cpp
compiling ../../src/Macro.cpp
compiling ../../src/MarkupParser.cpp
compiling ../../src/Math.cpp
compiling ../../src/OffScreenTarget.cpp
compiling ../../src/Resolution.cpp
compiling ../../src/RubyGosu.cxx
compiling ../../src/SDL_sound.c
In file included from ../../src/SDL_sound.c:1:
/Users/user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/gosu-1.2.0/dependencies/SDL_sound/SDL_sound.c:208:15: warning: implicit conversion loses integer precision: 'SDL_threadID' (aka 'unsigned long') to 'Uint32' (aka 'unsigned int') [-Wshorten-64-to-32]
        tid = SDL_ThreadID();
            ~ ^~~~~~~~~~~~~~
/Users/user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/gosu-1.2.0/dependencies/SDL_sound/SDL_sound.c:281:20: warning: implicit conversion loses integer precision: 'SDL_threadID' (aka 'unsigned long') to 'Uint32' (aka 'unsigned int') [-Wshorten-64-to-32]
        err->tid = SDL_ThreadID();
                 ~ ^~~~~~~~~~~~~~
/Users/user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/gosu-1.2.0/dependencies/SDL_sound/SDL_sound.c:392:15: warning: implicit conversion loses integer precision: 'Sint64' (aka 'long long') to 'int' [-Wshorten-64-to-32]
    int pos = SDL_RWtell(internal->rw);
        ~~~   ^~~~~~~~~~~~~~~~~~~~~~~~
3 warnings generated.
compiling ../../src/SDL_sound_aiff.c
In file included from ../../src/SDL_sound_aiff.c:1:

**Comment by jlnr** [comment]
Is this really the full output? Because it only contains warnings, no errors. And it looks like the last line is cut off ("In file included from"... what?)

**Comment by almokhtarbr** [comment]
@jlnr thank you so much for you response been waiting for 2 weeks 😆, 
no this is not the full output i didn't share it so long so take a look please here: [https://pastebin.com/KmyM6siP](https://pastebin.com/KmyM6siP)

**Comment by almokhtarbr** [comment]
Hi @jlnr, i made a virtual machine and installed in linux mint and it works like charm !! if that issue in mac mojave won't solved i will go with VM .
<img width="1280" alt="Screenshot 2021-07-04 at 11 39 13" src="https://user-images.githubusercontent.com/26042050/124381855-7f249b80-dcbc-11eb-9edd-7a8deba90997.png">

**Comment by jlnr** [comment]
Hmm, I think this is an error with SDL 2 in Homebrew. Gosu links to the output of `sdl2-config --static-libs`, which seems to include CoreHaptics.framework even on macOS versions that don't have it.

This should be fixed in the Homebrew recipe or maybe SDL 2 itself, instead of through another workaround in Gosu itself. I'm going to close this, but if you decide to open a ticket on another project, please let me know.
