### ISSUE TITLE
Can't Trace source of the Error

### ISSUE THREAD

**Issue by ekrarefaz** [gosu/gosu#598]
8: from extended_gui.rb:497:in `<main>'
	7: from /var/lib/gems/2.7.0/gems/gosu-1.2.0/lib/gosu/patches.rb:64:in `tick'
	6: from /var/lib/gems/2.7.0/gems/gosu-1.2.0/lib/gosu/patches.rb:64:in `tick'
	5: from extended_gui.rb:147:in `draw'
	4: from extended_gui.rb:493:in `draw_menu'
	3: from extended_gui.rb:413:in `draw_albums'
	2: from extended_gui.rb:413:in `new'
	1: from /var/lib/gems/2.7.0/gems/gosu-1.2.0/lib/gosu/compat.rb:89:in `initialize'
/var/lib/gems/2.7.0/gems/gosu-1.2.0/lib/gosu/compat.rb:89:in `initialize': Cannot open file  (RuntimeError)

I am getting this error on my PC and the same code seems to work fine on another PC. I uninstalled and reinstalled Gosu but still not working. I didn't know where to look for help regarding gosu. 
OS: Ubuntu 20.04

**Comment by jlnr** [comment]
Is the other PC running Windows or macOS? A common issue when porting games to other operating systems is that filenames are case sensitive on Linux only, so loading an image called player.png as "Player.png" would work on Windows, but raise the error you quoted on Linux.

Sent from my iPhone

**Comment by ekrarefaz** [comment]
understandable, I'll keep that in mind when porting to other OS. The pc is running Windows so that might be the case. I spent too much time on the error so I went back to my last commit. Thank you for the fast reply. Appreciate it!
