### ISSUE TITLE
Odd problem: "Could not create window: GLX is not supported (RuntimeError)"

### ISSUE THREAD

**Issue by rubyFeedback** [gosu/gosu#617]
As superuser after installing gosu-1.4.0 I get this error:

    /root/.gem/gems/gosu-1.4.0/lib/gosu/swig_patches.rb:16:in `initialize': Could not create window: GLX is not supported (RuntimeError)

Not sure how or why but I used this on a .rb file that in the past used to work.

Perhaps something is wrong on my computer system on linux, but I am 100% sure the code worked
in the past. So perhaps something changed in gosu?

Either way, could perhaps the error message be improved? I can fix most everything, but right now I don't even know what is GLX.

Usually I assume that mesa handles this. Mesa is at version: 21.3.4

I am using the latest stable versions of SDL2. So specifically SDL2-2.0.20. All compiled from source.

Anyway, I just mention this here. Perhaps I may be able to fix the error at a later time but then I often
forget to report how I fixed it, so I just mention it here before I investigate further. :)

**Comment by jlnr** [comment]
Nothing should have changed in Gosu regarding window initialization, so please retry with Gosu 1.2 to see if it isn't an error in your system configuration.

**Comment by jlnr** [comment]
I will also close this issue. I appreciate that you want to document your findings here, but building Linux from scratch and then getting GLX to work is outside of the scope of this issue tracker. Unless, of course, there has been an unintended breaking change in Gosu itself, in which case I'll be happy to revert it.
