### ISSUE TITLE
Gosu::Song using mojoAL is broken

### ISSUE THREAD

**Issue by cyberarm** [gosu/gosu#618]
1. Gosu::Song will start stuttering after successfully playing a few songs all the way through.
2. Additionally starting a song and then stopping it after a few seconds to start playing it again sounds like it is repeating the previous fed samples.

The first issue seemingly is caused an `AL_INVALID_OPERATION` for `alBufferData` in https://github.com/gosu/gosu/blob/1658882080f8ba12d251b4a91688c3fcd0031c95/src/Audio.cpp#L91-L100

Which is triggered by mojoAL reference counter: https://github.com/gosu/gosu/blob/1658882080f8ba12d251b4a91688c3fcd0031c95/dependencies/mojoAL/mojoal.c#L4450-L4458

The second issue may also be caused by the same issue, I haven't dug around for it yet, only noticed it when implementing a quick test for the first issue so I didn't need to wait 5 - 10 minutes for it to trigger.

Quick trigger project: https://github.com/cyberarm/mojoal_stutter_trigger

**Comment by cyberarm** [comment]
The second bug also appears to have the same cause: `alError stream_to_buffer-alBufferData : AL_INVALID_OPERATION`

**Comment by cyberarm** [comment]
Here is what it sounds like

https://user-images.githubusercontent.com/581879/150707337-e73dfb45-79e4-4427-9295-1d7fcaa45bb7.mp4

**Comment by cyberarm** [comment]
`AL_BUFFERS_QUEUED` (`alGetSourcei(source, AL_BUFFERS_QUEUED, &queued);`) may be returning an incorrect value
https://github.com/gosu/gosu/blob/1658882080f8ba12d251b4a91688c3fcd0031c95/dependencies/mojoAL/mojoal.c#L3724-L3726

https://github.com/gosu/gosu/blob/1658882080f8ba12d251b4a91688c3fcd0031c95/src/Audio.cpp#L145-L162

**Comment by cyberarm** [comment]
Adding a call to `alSourcei(source, AL_BUFFER, 0);` inside of `stop()` fixes these issues, except for `AL_BUFFERS_QUEUED` possibly not returning the correct number of buffers to unqueue; Causing the first sample of `song.play` after `song.stop` to be from the previous run for that song.

Maybe that this will get resolved by: https://github.com/icculus/mojoAL/issues/6

```cpp
    void stop()
    {
        ALuint source = al_source_for_songs();

        alSourceStop(source);

        /* ADDED */
        alSourcei(source, AL_BUFFER, 0);

        // Dequeue all buffers for this source.
        // The number of QUEUED buffers apparently includes the number of PROCESSED ones,
        // so getting rid of the QUEUED ones is enough.
        ALuint buffer;
        int queued;
        alGetSourcei(source, AL_BUFFERS_QUEUED, &queued);
        while (queued--) {
            alSourceUnqueueBuffers(source, 1, &buffer);
        }

        m_file->rewind();
    }
```

**Comment by jlnr** [comment]
Closing this, @cyberarm please let me know if I missed some parts of this that are still relevant.
