### ISSUE TITLE
Expose SDL2 *ClipboardText function bindings

### ISSUE THREAD

**Issue by Erquint** [gosu/gosu#629]
https://wiki.libsdl.org/CategoryClipboard
Pretty core to platform-independent OS integration that SDL2 is built for.

I have considered [the next best thing](https://www.ruby-toolbox.com/projects/clipboard) and its…
```rb
gem "ffi", :platforms => [:mswin, :mingw] # Required by Clipboard on Windows
```
> Important note for Linux users: The clipboard requires the xsel or the xclip command-line program. On debian and ubuntu, xsel can be installed with: sudo apt-get install xsel

…really doesn't speak fluent platform-agnostic approach to me.

**Comment by cyberarm** [comment]
This has been added by #630.
