### ISSUE TITLE
[Question] 3D games with GOSU or simulation of 3D games possible?

### ISSUE THREAD

**Issue by rubyFeedback** [gosu/gosu#632]
This is more a question.

There used to be the FIFE Engine:

https://www.fifengine.net/media.html
https://www.fifengine.net/img/screen5.png

Godot seems to replace it right now. Anyway.

I was wondering whether GOSU could be used for 3D games? Like the old
Fallout games, but also things such as Baldur's Gate 2 enhanced edition.

Note: I refer to a re-implementation, NOT the same game and same code.

Kind of how useful it would be, and whether it would even be possible,
to see that GOSU is not just for 2D games but also for 3D games.

That this may be too much work, is fine, I am more interested in the rationale
of how it may be possible (or impossible). Would be kind of nice to be able
to use ruby and "rewrite" tons of ancient games. :) (Or do some work and
others can continue etc...)

**Comment by jlnr** [comment]
In theory, you could use Gosu to open a window and then write 3D code inside a `gl {... }` block. However, then you have all the downsides of Gosu (hard to package your games, no web support) with the downsides of Ruby (slow performance). Not to mention that OpenGL is deprecated on Apple platforms.

I think it is just all-around wiser to write 3D games using a tool that abstracts most of this, like Godot, or one of the commercial engines.
